### ISSUE TITLE
Permissions on installed binary from the prebuilt pkg installer

### ISSUE THREAD

**Issue by sramdeen** [carlashley/appleloops#1]
Hi

First of all, thank you for releasing this new version. I am keen to try it out and so I have installed it on a test client and have noticed what may be a minor issue with the prebuilt package. I couldn't see anything in the release notes that indicates that this is expected behaviour and so I thought I'd post here.
The resulting appleloops in /usr/local/bin is installed with 744 perms, so only root is able to run it. The pkg BOM:

./usr/local/bin/appleloops	100744	0/0	30184	3441531849

When I try your instructions under "Building your own" the BOM shows the appleloops entry as 755 and this matches the installed binary's perms. 

Thanks again
Stuart

**Comment by carlashley** [comment]
Thanks :) The permissions issue should be resolved in v3.0.1.
