### ISSUE TITLE
Awesome work! Might want to fix typo

### ISSUE THREAD

**Issue by donmontalvo** [carlashley/appleLoops#10]
"./appleLoops.py --package-set garageband--mandatory-only"

Needs a space after "garageband".

**Comment by carlashley** [comment]
Thanks, and uh, yeah, just testing to make sure people are reading it... Well, that's my excuse and I'm sticking with it! :)

Fixed :)

**Comment by donmontalvo** [comment]
LOL...I'm stealing that one. :):):)
