### ISSUE TITLE
Hard links for locally downloaded packages?

### ISSUE THREAD

**Issue by apizz** [carlashley/appleLoops#11]
Was reading the documentation and noticed that duplicate content is copied.  Wondering why you would opt for making several copies of the same loop packages rather than use hard links.

In the event you have deployed multiple versions of GarageBand, for example, using hard links would avoid wasting unnecessary space with the same loop data when they are downloaded locally, or to a PKG server (looking to your test branch).

ex. `appleLoops.py --apps garageband -d ~/Downloads/Loops -m -o`

Would like some logic that if using the `-d` or `--pkg-server` that conserving space with hard links is an option.

**Comment by carlashley** [comment]
Yeah, good point re conserving space :)

The deployment feature doesn't need to worry about conserving space though as it will only be looking to download and install anything that isn't installed. Those loops get pulled into `/tmp`, installed, and then deleted.

In terms of downloading content for other uses or deployment styles, I've added `--hard-link` as an option.

**Comment by apizz** [comment]
Awesome!
