### ISSUE TITLE
Free space issue with Catalina

### ISSUE THREAD

**Issue by coalliera** [carlashley/appleloops#11]
When running appleloops with only mandatary files (around 5.71GB required), I got an error "Insufficient space to install packages"

Debug logs says:
Disk: /
Space used: 6136389476 (5.71GB)
Freespace: 0 (0 B)
Has enough space: False

I have 69GB available on my hard drive.

**Comment by carlashley** [comment]
Is this on the most recent release? If not, please try that first.

**Comment by coalliera** [comment]
Hi Carl,

I’m using the most recent pre build Apple loops and the latest catalina.

My computer is in French Canadian, I don’t know if it could cause an issue with the detection of the free space.

Sent from my iPhone

On Nov 28, 2019, at 3:21 PM, Carl <notifications@github.com> wrote:

﻿

Is this on the most recent release? If not, please try that first.

**Comment by carlashley** [comment]
Can you dump the output of `/usr/sbin/diskutil info -plist /` here? Sanitise anything that might be confidential/private information.

There's no language localizations, so if output of certain commands is localized, then yes, that's possibly the issue.

**Comment by carlashley** [comment]
I'm closing this issue - haven't heard back, and for all the tests I've done on macOS Catalina with https://github.com/carlashley/appleloops/releases/tag/v3.1.2 - the issue is resolved.

**Comment by coalliera** [comment]
Hi Carl, I sent you the information you asked last Tuesday.

Sent from my iPhone

On Dec 8, 2019, at 4:54 PM, Carl <notifications@github.com> wrote:

﻿

I'm closing this issue - haven't heard back, and for all the tests I've done on macOS Catalina with https://github.com/carlashley/appleloops/releases/tag/v3.1.2 - the issue is resolved.
