### ISSUE TITLE
--deployment option features?

### ISSUE THREAD

**Issue by apizz** [carlashley/appleLoops#12]
Know this feature is still in beta, but given some of our users use a combination of garageband, logicpro, and mainstage, and will install these through our Self Service portal at various times, I wondered if the `--deployment` option currently or will support the below scenarios so we can better support our users:

- User has one of the 3 apps above installed, and installs either mandatory or mandatory and optional loops.  Later, installs a different app and wants to install just the mandatory or mandatory and optional loops for the newly installed application.
- Same scenario as above, but only wanting to install loops not already installed (avoid reinstallation).
- Given many of our users have MacBook Airs and are therefore limited on storage space, account for space requirements in order to install mandatory or mandatory and optional loops.

Thanks for adding this feature in!  I recently finished our own bash script to accomplish something similar XD

**Comment by carlashley** [comment]
The way the `--deployment` feature works is it looks for any of the three apps (GarageBand, MainStage, Logic Pro X) at run time, and if it finds them, will install loops based on whatever arguments you've provided; it will skip any existing installed loops, or update if there are newer versions.

So if someone installs via self service, just run it again as a `postinstall`.

It basically boils down to what options you want to manage when deploying the apps (or through self service).

If space is a concern, then I'd only run it with the `-m/--mandatory-only` option to get those installed. You could then perhaps use a self service item that just runs `appleLoops.py` with the `-o/--optional-only` flag, if that makes sense.

In terms of checking if there is sufficient space to download the loops, that is something I want to add.

**Comment by apizz** [comment]
RE: checking for sufficient space - great!  Would this take into account the needed space minus any already installed packages that don't require an upgrade?

RE: `--deployment` glad to hear it won't reinstall a loop.  Does this mean that this check happens _before_ the loop is downloaded?  If so, that should be sufficient for us to deploy.

I'm imagining a deployment script that uses the `--plist` flag for the version of the app we make available in Self Service.  I incorrectly assumed that you couldn't define this with the `--deployment` command.

**Comment by carlashley** [comment]
I'm contemplating a check that takes into account the download size + install size for each package, so if it can install a package it will, but stop if it can't.

Yes - re `--deployment` the check to see if a package is installed happens before the file is downloaded.

At present, the `--plist` and `--deployment` commands can't be combined, my choice there is it has to look for the app first, and then use the plist contained in the app to figure out what loops need to be installed. As it turns out, these loops _do_ check to see if the app they're used with is installed per [this wiki article](https://github.com/carlashley/appleLoops/wiki/Understanding-Apple's-Audio-Content).

**Comment by apizz** [comment]
I would think a check that accounts for the cumulative download / install size of the specified packages would be better.  

For example a `--plist garageband1030.plist -m` would account for the total download size of all the mandatory packages for GarageBand to be downloaded.

However, in the case of using the `--deployment` option, it would account for the total **install** size of all selected packages (whether `-m`, `-o`, or both).  The total download size wouldn't matter as much because each package is being downloaded individually, installed, and then deleted.

RE: the combining of `--plist` & `--deployment`, how then would you specify the loops for the specific app you want to deploy?  `--apps`?  I want to be able to be able to use the `--deployment` option but also specify the app so I could incorporate this script for downloading and installing the necessary loops via a Self Service policy.  Don't want loops to be rechecked for other apps that may have already been installed via the same method previously

Separate but related idea:
Maybe there is an opportunity for a kind of `--threshold` flag in combination with `--deployment` which would allow you to specify a required amount of free space that is needed to be available _after_ install.  

For example, suppose there is sufficient free space to install all mandatory loops for GarageBand, but would result in only a few GBs of free space remaining.  Using the `--threshold` flag and providing an integer - 15 for example - the script would take the total available free space on the machine and subtract the amount of space the selected loop installs would take up.  If the resulting number is less than the provided `--threshold` value, the deployment would be cancelled.  This way, admins can help to ensure users don't unintentionally bloat up their computers with all these loops.

**Comment by apizz** [comment]
Just finished testing our workflow for deploying loops via our caching server and noticed that in the appleLoops.log file that there's nothing that indicates the successful install (or failure) of each loop.

Would like this install logging added when `--deployment` is used.

**Comment by carlashley** [comment]
The success/fail of an install/upgrade to a package is now capture in the log. Commit: f7f377b

I'm not planning on combining `--plist` and `--deployment`, or `--app` and `--deployment` as the `--deployment` flag checks to see if GarageBand, Logic Pro X, and MainStage are installed. If any/all of those are installed, it then attempts to install any packages based on provided `-m/--mandatory`/`-o/--optional` flags provided. It skips any loops already installed, or upgrades if an upgrade is required - the loops have to be checked if they're installed anyways, it's an insignificant amount of time involved.

This means you simply just need to `./appleLoops.py --deployment -m` or `./appleLoops.py --deployment -m -o` to get loops installed.

I've created a bunch of wiki pages that explain the tool's behaviour, the [Deployment](../wiki/Deployment) wiki page has info about different deployment techniques that can be used with this tool.

The `--threshold` free space idea is a feature I'm open to adding in a future release;  I've added disk space checks to version 2.0.7+ to ensure there is enough space available to download + install when `--deployment` mode is being used.

**Comment by carlashley** [comment]
I should clarify, the disk space checking implemented in 2.0.7 checks before download that there is enough space to download+install the package, if there isn't, it won't download it.

The install routine checks there is enough space to install it, and won't install if there isn't.

Additionally, the `installer` builtin also does its own disk space checks, so there's at least three levels of checks.

**Comment by carlashley** [comment]
`-t/--threshold` flag added in 28ca229.

Closing.

**Comment by apizz** [comment]
Awesome awesome awesome!!!  This is **so** great and will make me and my colleagues lives (and I imaging many more!) much much easier.

Just to be clear given your comments 8 hrs ago vs an hour ago and looking at the code, using the `-t/--threshold` flag and an integer will verify that the total space needed to install the loops is greater than the provided integer, otherwise it will not download the loops?

**Comment by carlashley** [comment]
So the `-t/--threshold` feature is an integer representing the percentage of free space you want to 'reserve' (that is keep free).

So for a system with 90GB of free space, you may want to keep 10% of that as free space, so:
`./appleLoops.py --deployment -m --threshold 10` would reserve 9GB.

The new 'available' free space that the system can use is therefore 81GB, and if the loop deployment exceeds 81GB it _will not_ install the loops and then does an `exit(1)`.

I've chosen to not install the loops as the behaviour at present because each app will persist in attempting to install/upgrade any new mandatory loops (and possibly optional loops that have updates) until it's able to install them. I figure having no loops installed is as bad as having only several installed and the system persist with installing.

The `--dry-run` feature is _not_ affected by this change, so it will still show what would be installed if there was enough disk space, instead it will advise that the loops will not install as there is insufficient space.

Example with enough space:
```
[user@helios]:~ # ./appleLoops.py --dry-run --deployment -m --log-path ~/Desktop/ --threshold 10
...
Download: MAContent10_AssetPack_0310_UB_DrumMachineDesignerGB.pkg (Package size: 18.71 MB  Installed size: 29.47 MB)
  Install: MAContent10_AssetPack_0310_UB_DrumMachineDesignerGB.pkg
Download: MAContent10_AssetPack_0357_EXS_BassAcousticUprightJazz.pkg (Package size: 15.53 MB  Installed size: 25.06 MB)
  Install: MAContent10_AssetPack_0357_EXS_BassAcousticUprightJazz.pkg
Download: MAContent10_AssetPack_0312_UB_UltrabeatKitsGBLogic.pkg (Package size: 26.12 MB  Installed size: 30.10 MB)
  Install: MAContent10_AssetPack_0312_UB_UltrabeatKitsGBLogic.pkg
---------------
Download total size: 2.00 GB  Install total size: 2.49 GB
Free space (threshold applied): 57.53 GB
Protected free space: 6.39 GB
All loops will be installed, sufficient free space
```

Example with insufficient space:
```
[user@helios]:~ # ./appleLoops.py --dry-run --deployment -m --log-path ~/Desktop/ --threshold 10
...
Download: MAContent10_AssetPack_0310_UB_DrumMachineDesignerGB.pkg (Package size: 18.71 MB  Installed size: 29.47 MB)
  Install: MAContent10_AssetPack_0310_UB_DrumMachineDesignerGB.pkg
Download: MAContent10_AssetPack_0357_EXS_BassAcousticUprightJazz.pkg (Package size: 15.53 MB  Installed size: 25.06 MB)
  Install: MAContent10_AssetPack_0357_EXS_BassAcousticUprightJazz.pkg
Download: MAContent10_AssetPack_0312_UB_UltrabeatKitsGBLogic.pkg (Package size: 26.12 MB  Installed size: 30.10 MB)
  Install: MAContent10_AssetPack_0312_UB_UltrabeatKitsGBLogic.pkg
---------------
Download total size: 2.00 GB  Install total size: 2.49 GB
Free space (threshold applied): 654.58 MB
Protected free space: 63.28 GB
No loops will be installed, as 63.28 GB is the required free space.
```
