### ISSUE TITLE
Error when pushed with an MDM

### ISSUE THREAD

**Issue by coalliera** [carlashley/appleloops#12]
When I push a script that run appleloops with my MDM, I got a free disk space error (see attached debug log).

I don't have this issue when I manually run the script on the same device.

Is there an option to skip free space verification?

"/usr/sbin/diskutil info -plist /" result is the same when pushed from my MDM or manually.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AESHardware</key>
	<false/>
	<key>APFSContainerFree</key>
	<integer>71148683264</integer>
	<key>APFSContainerReference</key>
	<string>disk1</string>
	<key>APFSContainerSize</key>
	<integer>121123069952</integer>
	<key>APFSPhysicalStores</key>
	<array>
		<dict>
			<key>APFSPhysicalStore</key>
			<string>disk0s2</string>
		</dict>
	</array>
	<key>APFSVolumeGroupID</key>
	<string>8139EAD0-C606-4F2F-A048-4FF9D7EB9A54</string>
	<key>Bootable</key>
	<true/>
	<key>BooterDeviceIdentifier</key>
	<string>disk1s2</string>
	<key>BusProtocol</key>
	<string>PCI</string>
	<key>CanBeMadeBootable</key>
	<false/>
	<key>CanBeMadeBootableRequiresDestroy</key>
	<false/>
	<key>Content</key>
	<string>41504653-0000-11AA-AA11-00306543ECAC</string>
	<key>DeviceBlockSize</key>
	<integer>4096</integer>
	<key>DeviceIdentifier</key>
	<string>disk1s5</string>
	<key>DeviceNode</key>
	<string>/dev/disk1s5</string>
	<key>DeviceTreePath</key>
	<string>IODeviceTree:/PCI0@0/RP06@1C,5/SSD0@0/PRT0@0/PMP@0</string>
	<key>DiskUUID</key>
	<string>B19C3A59-5847-49F7-B6FA-4ECC368FDE45</string>
	<key>Ejectable</key>
	<false/>
	<key>EjectableMediaAutomaticUnderSoftwareControl</key>
	<false/>
	<key>EjectableOnly</key>
	<false/>
	<key>Encryption</key>
	<false/>
	<key>FileVault</key>
	<false/>
	<key>FilesystemName</key>
	<string>APFS</string>
	<key>FilesystemType</key>
	<string>apfs</string>
	<key>FilesystemUserVisibleName</key>
	<string>APFS</string>
	<key>FreeSpace</key>
	<integer>0</integer>
	<key>Fusion</key>
	<false/>
	<key>GlobalPermissionsEnabled</key>
	<true/>
	<key>IOKitSize</key>
	<integer>121123069952</integer>
	<key>IORegistryEntryName</key>
	<string>Macintosh HD</string>
	<key>Internal</key>
	<true/>
	<key>Locked</key>
	<false/>
	<key>MediaName</key>
	<string></string>
	<key>MediaType</key>
	<string>Generic</string>
	<key>MountPoint</key>
	<string>/</string>
	<key>ParentWholeDisk</key>
	<string>disk1</string>
	<key>PartitionMapPartition</key>
	<false/>
	<key>RAIDMaster</key>
	<false/>
	<key>RAIDSlice</key>
	<false/>
	<key>RecoveryDeviceIdentifier</key>
	<string>disk1s3</string>
	<key>Removable</key>
	<false/>
	<key>RemovableMedia</key>
	<false/>
	<key>RemovableMediaOrExternalDevice</key>
	<false/>
	<key>SMARTDeviceSpecificKeysMayVaryNotGuaranteed</key>
	<dict/>
	<key>SMARTStatus</key>
	<string>Verified</string>
	<key>Size</key>
	<integer>121123069952</integer>
	<key>SolidState</key>
	<true/>
	<key>SupportsGlobalPermissionsDisable</key>
	<true/>
	<key>SystemImage</key>
	<false/>
	<key>TotalSize</key>
	<integer>121123069952</integer>
	<key>VolumeAllocationBlockSize</key>
	<integer>4096</integer>
	<key>VolumeName</key>
	<string>Macintosh HD</string>
	<key>VolumeSize</key>
	<integer>0</integer>
	<key>VolumeUUID</key>
	<string>B19C3A59-5847-49F7-B6FA-4ECC368FDE45</string>
	<key>WholeDisk</key>
	<false/>
	<key>Writable</key>
	<false/>
	<key>WritableMedia</key>
	<true/>
	<key>WritableVolume</key>
	<false/>
</dict>
</plist>

[appleloops.log](https://github.com/carlashley/appleloops/files/3941894/appleloops.log)

**Comment by carlashley** [comment]
Please run `appleloops.py --version` on the machine that has this problem and post the output here.

**Comment by coalliera** [comment]
"appleloops 3.1.2 (Apache License, Version 2.0)"

My MDM is downloading and executing the script from /tmp .
If I manually run the same script already downloaded by the MDM, then it works!

This issue occurs on many 2015 Macbook Air.

I tested the same workflow (script run by the MDM) on a 2018 Macbook Air and it works well

**Comment by carlashley** [comment]
Which MDM, what’s the contents of the script?
What happens when you add `--target /Volumes/Macintosh HD` to the appleloops command?

**Comment by coalliera** [comment]
I'm using Jamf School.

The Script it very simple:
` curl -L https://github.com/carlashley/appleloops/raw/master/appleloops --output /tmp/appleloops.py`
`python /tmp/appleloops.py --deployment -m -l DEBUG`

I will test --target next Tuesday.

**Comment by carlashley** [comment]
Using cURL to stream the file to disk is not a supported deployment method. Deploy the package that is pre built.
I’d also recommend checking out the #musicsupport channel in the Macadmins Slack - I don’t use JAMF so I can’t be very helpful there with regards to troubleshooting why it’s failing using that MDM process.

**Comment by coalliera** [comment]
Hi Carlashley, I made more tests and discovered the issue is only happening on macOS 10.15 everything works well with macOS 10.15.1

The issue seems to come from here: 
` if config.CATALINA:
            self._freespace_key = 'APFSContainerFree'
        else:
            self._freespace_key = 'FreeSpace'`

On macOS 10.15, self._freespace_key was set to FreeSpace and FreeSpace was equal to 0. I didn't looked why `config.CATALINA` was not detected on 10.15

**Comment by coalliera** [comment]
CATALINA = OS_VER >= LooseVersion('10.15.0')

is 10.15 => 10.15.0 ?

**Comment by carlashley** [comment]
> CATALINA = OS_VER >= LooseVersion('10.15.0')
> 
> is 10.15 => 10.15.0 ?

Quite likely the culprit. I'll correct that later today (my timezone).
If you need to get moving with your deployment, change the line in `config.py`:

**From**
```CATALINA = OS_VER >= LooseVersion('10.15.0')```

**To**
```CATALINA = OS_VER >= LooseVersion('10.14.9')```

**Comment by carlashley** [comment]
@coalliera - [v3.1.3](https://github.com/carlashley/appleloops/releases/tag/v3.1.3) should resolve this issue.
