### ISSUE TITLE
Second mirror!

### ISSUE THREAD

**Issue by makeworld-the-better-one** [carlashley/appleloops#14]
I'm not sure how useful this is to you, but I've set up a second mirror of all the pkgs at https://archive.org/download/lp10_ms3_content_2016 . Maybe it could work as a fallback mirror, after the direct Apple one, in case that goes down, or Apple removes the content?

**Comment by carlashley** [comment]
I appreciate the sentiment/thought process, but I'm not planning on adding any further layers of fallback.
