### ISSUE TITLE
Add command-line verbosity

### ISSUE THREAD

**Issue by apizz** [carlashley/appleLoops#14]
Would like the option to have the command-line output be more verbose that may or may not be in the logs to include:

- Queries & responses to/from caching server / pkg server
- Copy / hard link packages

**Comment by carlashley** [comment]
Not sure what you mean...

In the 2.0.5 release I've fixed a bug where the process would not copy/hard link a file even though it was present, and it now logs that to `stdout`.

The logs should be catching when the process falls back to using the Apple servers, but that's pretty easy to also include in `stdout`. Will double check when I can get back to the project.

**Comment by carlashley** [comment]
I'm not planning on adding any additional verbosity for CLI output as it's verbose enough as it is.
