### ISSUE TITLE
Downloads only server responses

### ISSUE THREAD

**Issue by gaming-hacker** [carlashley/appleloops#15]
**Describe the bug**
Content is not download, only server response.

**Version**
master

**Command Used**
appleloops --plists garageband1011 -m -o -f /Volumes/Apps_Media/Library/gb1011

**Debug Log**
none

This is what is received,  no content.

HTTP/1.1 200 OK
Server: Apache
Last-Modified: Tue, 13 Aug 2019 22:37:13 GMT
ETag: "b48782-5900748235840"
Accept-Ranges: bytes
Content-Length: 11831170
Content-Type: application/vnd.apple.installer+xml
Cache-Control: max-age=14400
Expires: Fri, 10 Jan 2020 02:00:44 GMT
Date: Thu, 09 Jan 2020 22:00:44 GMT
X-Cache: TCP_HIT from a23-62-99-124.deploy.akamaitechnologies.com (AkamaiGHost/9.8.5.1.1-27758809) (-)
Connection: keep-alive

**Comment by museum-future** [comment]
I tried it with this command
`appleloops -p garageband1011 -m -o -f ~/repo/loops`

it downloaded server response information in the .pkg file and didn't respect the -f flag

**Comment by carlashley** [comment]
I've not been able to replicate this issue with v3.1.3. 
Please post debug logs.

**Comment by carlashley** [comment]
I've not been able to replicate, and there's been no further updates to this. I'm closing this.
