### ISSUE TITLE
New PLISTs for Updated logicpro & mainstage versions

### ISSUE THREAD

**Issue by apizz** [carlashley/appleLoops#16]
See that you recently added a new plist for logicpro 10.3.2, but there is also an updated version of mainstage - 3.3.1 (up from 3.3.0) - which I did not see added.

**Comment by daveweale** [comment]
I don't think there are changes to the loops for Mainstage 3.3.1 from 3.3.0. If you investigate the app bundle (ctrl click, show package content) the embedded plist is the same as for 3.3.0. 

/Applications/MainStage\ 3.app/Contents/Resources/mainstage330.plist

Applications/MainStage\ 3.app/Contents/version.plist shows
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildAliasOf</key>
	<string>MAMainStage</string>
	<key>BuildVersion</key>
	<string>2</string>
	<key>CFBundleShortVersionString</key>
	<string>3.3.1</string>
	<key>CFBundleVersion</key>
	<string>4685.58</string>
	<key>ProductBuildVersion</key>
	<string>3M59</string>
	<key>ProjectName</key>
	<string>MAMainStage</string>
	<key>SourceVersion</key>
	<string>4685056000000000</string>
</dict>
</plist>

**Comment by carlashley** [comment]
@daveweale is correct. No new content for MainStage.
