### ISSUE TITLE
Local DMG Deployment fails

### ISSUE THREAD

**Issue by andbrowny** [carlashley/appleloops#17]
**Describe the bug**
When attempting to deploy packages contained in a DMG file on a local storage device (USB), as per instructions 
https://github.com/carlashley/appleloops/wiki/Local-DMG-Deployment, produces error saying "mirror server url format expected is https://example.org/<path> or https://example.org/file.dmg"

**Version**
3.1.4

**Commands Used**
Command Used to build dmg
appleloops -b ~/Desktop/garageband.dmg -a garageband -m -o

copy resulting dmg to external USB drive

Command Used to try to install pkgs from dmg
appleloops --deployment -a garageband --pkg-server /Volumes/ExternalUSB/appleLoops.dmg -m -o

**Debug Log**
nothing logged in either log for this error

**Screenshots**
N/A

**Comment by carlashley** [comment]
Give the package pushed in b1168d9 a whirl. That should resolve the issue for you.

**Comment by carlashley** [comment]
My bad, just realised the `pkg` folder is in `.gitignore`. Try the `appleloops` file in the root of this repo (it will be version 3.1.5).

**Comment by andbrowny** [comment]
Thanks for that Carl, I worked around the pkg directory issue and managed to build a 3.1.5 version which worked fine.
