### ISSUE TITLE
--deployment downloads and reinstalls already installed loops

### ISSUE THREAD

**Issue by apizz** [carlashley/appleLoops#17]
Testing on 2.0.9 confirmed that running `--deployment` all mandatory loops redownloaded and reinstalled.

See Terminal output below and attached log.
[appleLoops.log.zip](https://github.com/carlashley/appleLoops/files/1187872/appleLoops.log.zip)

`sudo appleLoops.py --deployment -m -c http://XX.XX.XX.XX:59400
Password:
Loops downloading to: /tmp
Caching Server: http://XX.XX.XX.XX:59400
Processing loops from: garageband1020.plist
Downloading: MAContent10_AssetPack_0539_DrummerTambourine.pkg (Package size: 19.75 MB  Installed size: 34.63 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0539_DrummerTambourine.pkg
  Installed: MAContent10_AssetPack_0539_DrummerTambourine.pkg
Downloading: MAContent10_AssetPack_0324_AppleLoopsBluesGarage.pkg (Package size: 30.87 MB  Installed size: 34.84 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0324_AppleLoopsBluesGarage.pkg
  Installed: MAContent10_AssetPack_0324_AppleLoopsBluesGarage.pkg
Downloading: MAContent10_AssetPack_0536_DrummerClapsCowbell.pkg (Package size: 17.91 MB  Installed size: 32.19 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0536_DrummerClapsCowbell.pkg
  Installed: MAContent10_AssetPack_0536_DrummerClapsCowbell.pkg
Downloading: MAContent10_AssetPack_0322_AppleLoopsDiscoFunk1.pkg (Package size: 15.92 MB  Installed size: 20.76 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0322_AppleLoopsDiscoFunk1.pkg
  Installed: MAContent10_AssetPack_0322_AppleLoopsDiscoFunk1.pkg
Downloading: MAContent10_AssetPack_0315_AppleLoopsElectroHouse1.pkg (Package size: 40.00 MB  Installed size: 45.87 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0315_AppleLoopsElectroHouse1.pkg
  Installed: MAContent10_AssetPack_0315_AppleLoopsElectroHouse1.pkg
Downloading: MAContent10_AssetPack_0593_DrummerSoCalGBLogic.pkg (Package size: 240.83 MB  Installed size: 350.06 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0593_DrummerSoCalGBLogic.pkg
  Installed: MAContent10_AssetPack_0593_DrummerSoCalGBLogic.pkg
Downloading: MAContent10_AssetPack_0320_AppleLoopsChillwave1.pkg (Package size: 35.80 MB  Installed size: 41.50 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0320_AppleLoopsChillwave1.pkg
  Installed: MAContent10_AssetPack_0320_AppleLoopsChillwave1.pkg
Downloading: MAContent10_AssetPack_0646_AppleLoopsDrummerElectronic.pkg (Package size: 41.29 MB  Installed size: 58.95 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0646_AppleLoopsDrummerElectronic.pkg
  Installed: MAContent10_AssetPack_0646_AppleLoopsDrummerElectronic.pkg
Downloading: MAContent10_AssetPack_0375_EXS_GuitarsVintageStrat.pkg (Package size: 29.61 MB  Installed size: 48.93 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0375_EXS_GuitarsVintageStrat.pkg
  Installed: MAContent10_AssetPack_0375_EXS_GuitarsVintageStrat.pkg
Downloading: MAContent10_AssetPack_0316_AppleLoopsDubstep1.pkg (Package size: 7.10 MB  Installed size: 8.44 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0316_AppleLoopsDubstep1.pkg
  Installed: MAContent10_AssetPack_0316_AppleLoopsDubstep1.pkg
Downloading: MAContent10_AssetPack_0597_LTPChordTrainer.pkg (Package size: 14.68 MB  Installed size: 105.32 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0597_LTPChordTrainer.pkg
  Installed: MAContent10_AssetPack_0597_LTPChordTrainer.pkg
Downloading: MAContent10_AssetPack_0509_EXS_StringsEnsemble.pkg (Package size: 47.70 MB  Installed size: 49.62 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0509_EXS_StringsEnsemble.pkg
  Installed: MAContent10_AssetPack_0509_EXS_StringsEnsemble.pkg
Downloading: MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg (Package size: 27.73 MB  Installed size: 31.67 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg
  Installed: MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg
Downloading: MAContent10_AssetPack_0554_AppleLoopsDiscoFunk2.pkg (Package size: 19.51 MB  Installed size: 23.22 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0554_AppleLoopsDiscoFunk2.pkg
  Installed: MAContent10_AssetPack_0554_AppleLoopsDiscoFunk2.pkg
Downloading: MAContent10_AssetPack_0358_EXS_BassElectricFingerStyle.pkg (Package size: 34.58 MB  Installed size: 44.05 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0358_EXS_BassElectricFingerStyle.pkg
  Installed: MAContent10_AssetPack_0358_EXS_BassElectricFingerStyle.pkg
Downloading: MAContent10_AssetPack_0540_PlugInSettingsGB.pkg (Package size: 107.98 KB  Installed size: 164.09 KB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0540_PlugInSettingsGB.pkg
  Installed: MAContent10_AssetPack_0540_PlugInSettingsGB.pkg
Downloading: MAContent10_AssetPack_0371_EXS_GuitarsAcoustic.pkg (Package size: 28.66 MB  Installed size: 49.20 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0371_EXS_GuitarsAcoustic.pkg
  Installed: MAContent10_AssetPack_0371_EXS_GuitarsAcoustic.pkg
Downloading: MAContent10_AssetPack_0537_DrummerShaker.pkg (Package size: 11.11 MB  Installed size: 19.26 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0537_DrummerShaker.pkg
  Installed: MAContent10_AssetPack_0537_DrummerShaker.pkg
Downloading: MAContent10_AssetPack_0323_AppleLoopsVintageBreaks.pkg (Package size: 33.34 MB  Installed size: 36.36 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0323_AppleLoopsVintageBreaks.pkg
  Installed: MAContent10_AssetPack_0323_AppleLoopsVintageBreaks.pkg
Downloading: MAContent10_AssetPack_0048_AlchemyPadsDigitalHolyGhost.pkg (Package size: 11.27 MB  Installed size: 13.28 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0048_AlchemyPadsDigitalHolyGhost.pkg
  Installed: MAContent10_AssetPack_0048_AlchemyPadsDigitalHolyGhost.pkg
Downloading: MAContent10_AssetPack_0317_AppleLoopsModernRnB1.pkg (Package size: 16.60 MB  Installed size: 18.29 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0317_AppleLoopsModernRnB1.pkg
  Installed: MAContent10_AssetPack_0317_AppleLoopsModernRnB1.pkg
Downloading: MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg (Package size: 25.70 MB  Installed size: 29.62 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg
  Installed: MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg
Downloading: MAContent10_AssetPack_0314_AppleLoopsHipHop1.pkg (Package size: 152.69 MB  Installed size: 162.65 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0314_AppleLoopsHipHop1.pkg
  Installed: MAContent10_AssetPack_0314_AppleLoopsHipHop1.pkg
Downloading: MAContent10_AssetPack_0482_EXS_OrchWoodwindAltoSax.pkg (Package size: 21.96 MB  Installed size: 23.33 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0482_EXS_OrchWoodwindAltoSax.pkg
  Installed: MAContent10_AssetPack_0482_EXS_OrchWoodwindAltoSax.pkg
Downloading: MAContent10_AssetPack_0538_DrummerSticks.pkg (Package size: 803.95 KB  Installed size: 1.13 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0538_DrummerSticks.pkg
  Installed: MAContent10_AssetPack_0538_DrummerSticks.pkg
Downloading: MAContent10_AssetPack_0325_AppleLoopsGarageBand1.pkg (Package size: 20.69 MB  Installed size: 22.11 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0325_AppleLoopsGarageBand1.pkg
  Installed: MAContent10_AssetPack_0325_AppleLoopsGarageBand1.pkg
Downloading: MAContent10_AssetPack_0354_EXS_PianoSteinway.pkg (Package size: 139.18 MB  Installed size: 175.65 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0354_EXS_PianoSteinway.pkg
  Installed: MAContent10_AssetPack_0354_EXS_PianoSteinway.pkg
Downloading: MAContent10_AssetPack_0491_EXS_OrchBrass.pkg (Package size: 185.96 MB  Installed size: 211.85 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0491_EXS_OrchBrass.pkg
  Installed: MAContent10_AssetPack_0491_EXS_OrchBrass.pkg
Downloading: MAContent10_AssetPack_0598_LTPBasicGuitar1.pkg (Package size: 275.39 MB  Installed size: 282.81 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0598_LTPBasicGuitar1.pkg
  Installed: MAContent10_AssetPack_0598_LTPBasicGuitar1.pkg
Downloading: MAContent10_AssetPack_0321_AppleLoopsIndieDisco.pkg (Package size: 15.68 MB  Installed size: 19.29 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0321_AppleLoopsIndieDisco.pkg
  Installed: MAContent10_AssetPack_0321_AppleLoopsIndieDisco.pkg
Downloading: MAContent10_AssetPack_0615_GBLogicAlchemyEssentials.pkg (Package size: 204.80 MB  Installed size: 233.28 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0615_GBLogicAlchemyEssentials.pkg
  Installed: MAContent10_AssetPack_0615_GBLogicAlchemyEssentials.pkg
Downloading: MAContent10_AssetPack_0637_AppleLoopsDrummerKyle.pkg (Package size: 3.85 MB  Installed size: 4.10 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0637_AppleLoopsDrummerKyle.pkg
  Installed: MAContent10_AssetPack_0637_AppleLoopsDrummerKyle.pkg
Downloading: MAContent10_AssetPack_0560_LTPBasicPiano1.pkg (Package size: 216.74 MB  Installed size: 223.34 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0560_LTPBasicPiano1.pkg
  Installed: MAContent10_AssetPack_0560_LTPBasicPiano1.pkg
Downloading: MAContent10_AssetPack_0310_UB_DrumMachineDesignerGB.pkg (Package size: 18.71 MB  Installed size: 29.47 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0310_UB_DrumMachineDesignerGB.pkg
  Installed: MAContent10_AssetPack_0310_UB_DrumMachineDesignerGB.pkg
Downloading: MAContent10_AssetPack_0357_EXS_BassAcousticUprightJazz.pkg (Package size: 15.53 MB  Installed size: 25.06 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0357_EXS_BassAcousticUprightJazz.pkg
  Installed: MAContent10_AssetPack_0357_EXS_BassAcousticUprightJazz.pkg
Downloading: MAContent10_AssetPack_0312_UB_UltrabeatKitsGBLogic.pkg (Package size: 26.12 MB  Installed size: 30.10 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0312_UB_UltrabeatKitsGBLogic.pkg
  Installed: MAContent10_AssetPack_0312_UB_UltrabeatKitsGBLogic.pkg
Finished run at 2017-07-31 10:28:34
casperTEST3:~ ap.orlebeke$ sudo appleLoops.py --deployment -m -c http://XX.XX.XX.XX:59400
Loops downloading to: /tmp
Caching Server: http://XX.XX.XX.XX:59400
Processing loops from: garageband1020.plist
Downloading: MAContent10_AssetPack_0539_DrummerTambourine.pkg (Package size: 19.75 MB  Installed size: 34.63 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0539_DrummerTambourine.pkg
  Installed: MAContent10_AssetPack_0539_DrummerTambourine.pkg
Downloading: MAContent10_AssetPack_0324_AppleLoopsBluesGarage.pkg (Package size: 30.87 MB  Installed size: 34.84 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0324_AppleLoopsBluesGarage.pkg
  Installed: MAContent10_AssetPack_0324_AppleLoopsBluesGarage.pkg
Downloading: MAContent10_AssetPack_0536_DrummerClapsCowbell.pkg (Package size: 17.91 MB  Installed size: 32.19 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0536_DrummerClapsCowbell.pkg
  Installed: MAContent10_AssetPack_0536_DrummerClapsCowbell.pkg
Downloading: MAContent10_AssetPack_0322_AppleLoopsDiscoFunk1.pkg (Package size: 15.92 MB  Installed size: 20.76 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0322_AppleLoopsDiscoFunk1.pkg
  Installed: MAContent10_AssetPack_0322_AppleLoopsDiscoFunk1.pkg
Downloading: MAContent10_AssetPack_0315_AppleLoopsElectroHouse1.pkg (Package size: 40.00 MB  Installed size: 45.87 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0315_AppleLoopsElectroHouse1.pkg
  Installed: MAContent10_AssetPack_0315_AppleLoopsElectroHouse1.pkg
Downloading: MAContent10_AssetPack_0593_DrummerSoCalGBLogic.pkg (Package size: 240.83 MB  Installed size: 350.06 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0593_DrummerSoCalGBLogic.pkg
  Installed: MAContent10_AssetPack_0593_DrummerSoCalGBLogic.pkg
Downloading: MAContent10_AssetPack_0320_AppleLoopsChillwave1.pkg (Package size: 35.80 MB  Installed size: 41.50 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0320_AppleLoopsChillwave1.pkg
  Installed: MAContent10_AssetPack_0320_AppleLoopsChillwave1.pkg
Downloading: MAContent10_AssetPack_0646_AppleLoopsDrummerElectronic.pkg (Package size: 41.29 MB  Installed size: 58.95 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0646_AppleLoopsDrummerElectronic.pkg
  Installed: MAContent10_AssetPack_0646_AppleLoopsDrummerElectronic.pkg
Downloading: MAContent10_AssetPack_0375_EXS_GuitarsVintageStrat.pkg (Package size: 29.61 MB  Installed size: 48.93 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0375_EXS_GuitarsVintageStrat.pkg
  Installed: MAContent10_AssetPack_0375_EXS_GuitarsVintageStrat.pkg
Downloading: MAContent10_AssetPack_0316_AppleLoopsDubstep1.pkg (Package size: 7.10 MB  Installed size: 8.44 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0316_AppleLoopsDubstep1.pkg
  Installed: MAContent10_AssetPack_0316_AppleLoopsDubstep1.pkg
Downloading: MAContent10_AssetPack_0597_LTPChordTrainer.pkg (Package size: 14.68 MB  Installed size: 105.32 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0597_LTPChordTrainer.pkg
  Installed: MAContent10_AssetPack_0597_LTPChordTrainer.pkg
Downloading: MAContent10_AssetPack_0509_EXS_StringsEnsemble.pkg (Package size: 47.70 MB  Installed size: 49.62 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0509_EXS_StringsEnsemble.pkg
  Installed: MAContent10_AssetPack_0509_EXS_StringsEnsemble.pkg
Downloading: MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg (Package size: 27.73 MB  Installed size: 31.67 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg
  Installed: MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg
Downloading: MAContent10_AssetPack_0554_AppleLoopsDiscoFunk2.pkg (Package size: 19.51 MB  Installed size: 23.22 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0554_AppleLoopsDiscoFunk2.pkg
  Installed: MAContent10_AssetPack_0554_AppleLoopsDiscoFunk2.pkg
Downloading: MAContent10_AssetPack_0358_EXS_BassElectricFingerStyle.pkg (Package size: 34.58 MB  Installed size: 44.05 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0358_EXS_BassElectricFingerStyle.pkg
  Installed: MAContent10_AssetPack_0358_EXS_BassElectricFingerStyle.pkg
Downloading: MAContent10_AssetPack_0540_PlugInSettingsGB.pkg (Package size: 107.98 KB  Installed size: 164.09 KB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0540_PlugInSettingsGB.pkg
  Installed: MAContent10_AssetPack_0540_PlugInSettingsGB.pkg
Downloading: MAContent10_AssetPack_0371_EXS_GuitarsAcoustic.pkg (Package size: 28.66 MB  Installed size: 49.20 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0371_EXS_GuitarsAcoustic.pkg
  Installed: MAContent10_AssetPack_0371_EXS_GuitarsAcoustic.pkg
Downloading: MAContent10_AssetPack_0537_DrummerShaker.pkg (Package size: 11.11 MB  Installed size: 19.26 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0537_DrummerShaker.pkg
  Installed: MAContent10_AssetPack_0537_DrummerShaker.pkg
Downloading: MAContent10_AssetPack_0323_AppleLoopsVintageBreaks.pkg (Package size: 33.34 MB  Installed size: 36.36 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0323_AppleLoopsVintageBreaks.pkg
  Installed: MAContent10_AssetPack_0323_AppleLoopsVintageBreaks.pkg
Downloading: MAContent10_AssetPack_0048_AlchemyPadsDigitalHolyGhost.pkg (Package size: 11.27 MB  Installed size: 13.28 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0048_AlchemyPadsDigitalHolyGhost.pkg
  Installed: MAContent10_AssetPack_0048_AlchemyPadsDigitalHolyGhost.pkg
Downloading: MAContent10_AssetPack_0317_AppleLoopsModernRnB1.pkg (Package size: 16.60 MB  Installed size: 18.29 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0317_AppleLoopsModernRnB1.pkg
  Installed: MAContent10_AssetPack_0317_AppleLoopsModernRnB1.pkg
Downloading: MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg (Package size: 25.70 MB  Installed size: 29.62 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg
  Installed: MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg
Downloading: MAContent10_AssetPack_0314_AppleLoopsHipHop1.pkg (Package size: 152.69 MB  Installed size: 162.65 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0314_AppleLoopsHipHop1.pkg
  Installed: MAContent10_AssetPack_0314_AppleLoopsHipHop1.pkg
Downloading: MAContent10_AssetPack_0482_EXS_OrchWoodwindAltoSax.pkg (Package size: 21.96 MB  Installed size: 23.33 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0482_EXS_OrchWoodwindAltoSax.pkg
  Installed: MAContent10_AssetPack_0482_EXS_OrchWoodwindAltoSax.pkg
Downloading: MAContent10_AssetPack_0538_DrummerSticks.pkg (Package size: 803.95 KB  Installed size: 1.13 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0538_DrummerSticks.pkg
  Installed: MAContent10_AssetPack_0538_DrummerSticks.pkg
Downloading: MAContent10_AssetPack_0325_AppleLoopsGarageBand1.pkg (Package size: 20.69 MB  Installed size: 22.11 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0325_AppleLoopsGarageBand1.pkg
  Installed: MAContent10_AssetPack_0325_AppleLoopsGarageBand1.pkg
Downloading: MAContent10_AssetPack_0354_EXS_PianoSteinway.pkg (Package size: 139.18 MB  Installed size: 175.65 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0354_EXS_PianoSteinway.pkg
  Installed: MAContent10_AssetPack_0354_EXS_PianoSteinway.pkg
Downloading: MAContent10_AssetPack_0491_EXS_OrchBrass.pkg (Package size: 185.96 MB  Installed size: 211.85 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0491_EXS_OrchBrass.pkg
  Installed: MAContent10_AssetPack_0491_EXS_OrchBrass.pkg
Downloading: MAContent10_AssetPack_0598_LTPBasicGuitar1.pkg (Package size: 275.39 MB  Installed size: 282.81 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0598_LTPBasicGuitar1.pkg
  Installed: MAContent10_AssetPack_0598_LTPBasicGuitar1.pkg
Downloading: MAContent10_AssetPack_0321_AppleLoopsIndieDisco.pkg (Package size: 15.68 MB  Installed size: 19.29 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0321_AppleLoopsIndieDisco.pkg
  Installed: MAContent10_AssetPack_0321_AppleLoopsIndieDisco.pkg
Downloading: MAContent10_AssetPack_0615_GBLogicAlchemyEssentials.pkg (Package size: 204.80 MB  Installed size: 233.28 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0615_GBLogicAlchemyEssentials.pkg
  Installed: MAContent10_AssetPack_0615_GBLogicAlchemyEssentials.pkg
Downloading: MAContent10_AssetPack_0637_AppleLoopsDrummerKyle.pkg (Package size: 3.85 MB  Installed size: 4.10 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0637_AppleLoopsDrummerKyle.pkg
  Installed: MAContent10_AssetPack_0637_AppleLoopsDrummerKyle.pkg
Downloading: MAContent10_AssetPack_0560_LTPBasicPiano1.pkg (Package size: 216.74 MB  Installed size: 223.34 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0560_LTPBasicPiano1.pkg
  Installed: MAContent10_AssetPack_0560_LTPBasicPiano1.pkg
Downloading: MAContent10_AssetPack_0310_UB_DrumMachineDesignerGB.pkg (Package size: 18.71 MB  Installed size: 29.47 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0310_UB_DrumMachineDesignerGB.pkg
  Installed: MAContent10_AssetPack_0310_UB_DrumMachineDesignerGB.pkg
Downloading: MAContent10_AssetPack_0357_EXS_BassAcousticUprightJazz.pkg (Package size: 15.53 MB  Installed size: 25.06 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0357_EXS_BassAcousticUprightJazz.pkg
  Installed: MAContent10_AssetPack_0357_EXS_BassAcousticUprightJazz.pkg
Downloading: MAContent10_AssetPack_0312_UB_UltrabeatKitsGBLogic.pkg (Package size: 26.12 MB  Installed size: 30.10 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0312_UB_UltrabeatKitsGBLogic.pkg
  Installed: MAContent10_AssetPack_0312_UB_UltrabeatKitsGBLogic.pkg
Finished run at 2017-07-31 10:31:33`

**Comment by carlashley** [comment]
This should be fixed in 2.1.1 - commit cc04866. I've tested against GarageBand 10.2.0, then installing MainStage 3.x, followed by Logix Pro X afterwards, and re-running, it's only installed what was needed (this was for mandatory content only).
All apps launched fine without prompting to download the mandatory content.

**Comment by apizz** [comment]
Not sure if I'm getting issues because I'm running this on the same test machine which has now installed the mandatory loops a few times, but below is my Terminal output and attached log.

Log seems to say that all mandatory loops require upgrading.

[appleLoops.log.zip](https://github.com/carlashley/appleLoops/files/1190736/appleLoops.log.zip)

```
bash-3.2# appleLoops.py --deployment -m -c http://XX.XX.XX.XX:59400
Loops downloading to: /tmp
Caching Server: http://XX.XX.XX.XX:59400
Processing loops from: garageband1020.plist
Traceback (most recent call last):
  File "/usr/local/bin/appleLoops.py", line 1278, in <module>
    main()
  File "/usr/local/bin/appleLoops.py", line 1270, in main
    al.main_processor()
  File "/usr/local/bin/appleLoops.py", line 404, in main_processor
    if self.debug:
AttributeError: AppleLoops instance has no attribute 'debug'
```

**Comment by carlashley** [comment]
That should now be resolved in commit 01dbca2 (at least in my testing it has been).
It was an issue with the version numbers that are in the `pkginfo` for a given package ID and how `LooseVersion()/StrictVersion()` work when comparing a version that is `0.0.0` and `0.0.0.0.0`.
The `pkginfo` version string for the loops typically looks like: `2.0.0.0.1.1447702152` which when evaluated against something like `2.0.0` would always be _less_ than.

Resolved by trimming local version to `2.0.0`. I'm fairly confident that this won't cause issues with future package updates.

```
>>> from distutils.version import LooseVersion
>>> local_ver = '2.0.0.0.1.1447702152'
>>> remote_ver = '2.0.0'
>>> LooseVersion(local_ver) < LooseVersion(remote_ver)
False
>>> LooseVersion('.'.join(local_ver.split('.')[:3])) <= LooseVersion(remote_ver)
True
>>> LooseVersion('.'.join(local_ver.split('.')[:3])) < LooseVersion(remote_ver)
False
```

**Comment by apizz** [comment]
Confirmed that packages are not redownloaded and reinstalled!  Thank you.

Is it possible to include something in the log when no loops were downloaded or installed for a particular app?  I think this would be a helpful addition item in the log since by default it's looking to install loops for all possible apps.

**Comment by carlashley** [comment]
Heh, I'm pretty sure I had something logged out at then end of a run, but that escaped a commit.

I don't believe it should be done for each package, that just makes the log file overly verbose, but I've added a log entry that replicates the 'have a coffee' message.
