### ISSUE TITLE
Latest Orchestra Content Not Updating

### ISSUE THREAD

**Issue by aarondavidpolley** [carlashley/appleloops#18]
**Version**: 3.1.3

**Command Used**: primarily `/usr/local/bin/appleloops --deployment -c http://10.1.16.199:50466 -m -o -q` via Jamf

**Debug Log**: a few copies attached below

**Screenshots**: attached below

**Context**:
Had an interesting one over the last 2 weeks, where AD networked users in a Mac Lab running 10.15.3 kept getting new sounds available notification in notifications centre and some of the orchestral content was showing as needing update. 

Running AppleLoops in terminal, Jamf Self Service Policy, and regular monthly run via recurring Jamf policy showed that everything was up to date (using -m and -o flags, with and without caching server address)

Using Pkgutil to check for the packages I believed they were was showing as already installed and any attempts to "forget" them to force a re-install throws an error (likely due to it residing the read only volume)

I searched the hosted Plists for the packages I believed they were, downloaded and installed the content manually and voila it now shows as up to date in the sound library and no more notification centre prompts.

My users are not admins by default so crowd sourcing the resolution can't occur; I've had to deploy the updated packages via Jamf which once doing so has resolved the user experience.

I'm thinking Apple is using a different mechanism to show the packages have updates vs what AppleLoops is doing? Very odd...

Packages I needed to patch manually:

```
MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg
MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg
MAContent10_AssetPack_0491_EXS_OrchBrass.pkg
```

I don's have logs from the manual runs but I have debug and dry run in one log attached, and the results in Jamf from:

```
/usr/local/bin/appleloops --deployment -c http://10.1.16.199:50466 -m -o -q
```

Results:

```
[STEP 1 of 4]
--
Executing Policy appleLoops Run
[STEP 2 of 4]
Running script Run appleLoops 3...
Script exit code: 0
Script result: Installed apps found: GarageBand (10.3.4)Nothing to process. Exiting.
[STEP 3 of 4]
[STEP 4 of 4]
```

Post patching, here is some testing results:

```
COMPUTER:~ root# /usr/local/bin/appleloops --deployment -c http://10.1.16.199:50466 -m -o -n -l DEBUG
Analysing...
Installed apps found: GarageBand (10.3.4)
Nothing to process. Exiting.

COMPUTER:~ root# /usr/local/bin/appleloops --deployment -m -o -n -l DEBUG
Analysing...
Installed apps found: GarageBand (10.3.4)
Nothing to process. Exiting.
```

Logs from these attached as well

![Screen Shot 2020-03-23 at 10 43 58 am](https://user-images.githubusercontent.com/20986508/77269042-7ab8b700-6cf3-11ea-915a-36782ed43796.png)

![Screen Shot 2020-03-23 at 10 44 37 am](https://user-images.githubusercontent.com/20986508/77269064-899f6980-6cf3-11ea-8c09-96c74e125473.png)

![Screen Shot 2020-03-23 at 10 44 48 am](https://user-images.githubusercontent.com/20986508/77268658-5f997780-6cf2-11ea-893c-b644e5eb02c5.png)

[appleloops_DEBUG_DRY.log](https://github.com/carlashley/appleloops/files/4366689/appleloops_DEBUG_DRY.log)

[appleloops_nocache.log](https://github.com/carlashley/appleloops/files/4366789/appleloops_nocache.log)

[appleloops_withcache.log](https://github.com/carlashley/appleloops/files/4366790/appleloops_withcache.log)

**Comment by aarondavidpolley** [comment]
Minor note, the notification centre item for "New Sounds Available" is still appearing on the first launch of manually patches machines when a new user logs in, but when clicked there is nothing for it to do so it doesn't trigger any subsequent screens or admin password prompts.

**Comment by carlashley** [comment]
Hey @aarondavidpolley - as discussed in Slack, I think this is an issue on the Apple software side rather than an issue with the `appleloops.py` deployment process.

If the package receipts and files are correctly installed, which from discussion/logs they have been, then it is possible that this package hasn't been detected and may require a [manual re-index of the loops](https://support.apple.com/en-us/HT201368).
