### ISSUE TITLE
FR: Codes for different failures?

### ISSUE THREAD

**Issue by apizz** [carlashley/appleLoops#18]
After all the additional functionality added in 2.0.8, the thought occurred to me that if someone were to deploy this script via an MDM or other method and were to fail at some point during the process, it might be difficult to ascertain as part of their workflow what exactly went wrong.

As one example, recently I discovered that machines on the teacher wifi portion of our network were unable to communicate with our caching server to download these loops.  I'm wondering if there's an opportunity to add codes so when the appleLoops.py script is invoked (perhaps by another script) it can be determined what failures (if any) the exit status was related to.  This way too, admins could follow up any specific failures with a dialog box to inform the user that there's a particular issue when installed via Self Service.

Some thoughts are below:

- Failure for inability to communicate with specified caching server, pkg server
- Failure for insufficient free space to download loops ( when `-d` flag is used )
- Failure for insufficient free space to install loops ( when `--deployment` flag is used )
- Failure for one or more packages to download ( when caching server, pkg server, or Apple Internet download is used )
- Failure for one or more packages to install ( when `--deployment` flag is used)
- Failure for package copy or hard link creation when multiple apps are downloaded ( when `-d` flag is used )

**Comment by carlashley** [comment]
Certainly, it's also a good spot to remove a bunch of repeated code as well. Pretty much all non successful exits will have their own specific exit code as required. I.e. `exit(3)` represents the `Not root user` error. I've also decided that `/tmp` is just _too_ temporary, so default log directory is `~/Library/Logs` for whomever runs it where `--log-path` is not used to override.

I have some thoughts about these specific items:

- Failure to not communicate with caching server/pkg server
    - I'd suggest that if a caching server can't be used, then a fall back to Apple's servers should be preferred behaviour. This is a logged event in the upcoming 2.1.3 commit.
    - Current behaviour is to fall back to Apple's server if the specified package doesn't exist on the specified package server. This is a logged event in the upcoming 2.1.3 commit.
- Failure for one or more packages to install
    - If the download has failed, the install will fail. I've added a `failed_installs` list to track these failures, and it will provide this error in the logs and `stdout` as well as a relevant exit code. This will be in the 2.1.3 commit.

**Comment by carlashley** [comment]
@apizz So 2.1.3 is updated which includes a bunch of exit code stuff.
