### ISSUE TITLE
Download / Install Summary in Log?

### ISSUE THREAD

**Issue by apizz** [carlashley/appleLoops#20]
I seem to remember either in a post or README a summary of how much was downloaded and installed at the end of running appleLoops.py.

After completing a test install of mandatory loops for GarageBand I don't see this info in the appleLoops.log file.  This would be a nice addition as a point of comparison should subsequent installs take place, and to speak to the total size of everything downloaded compared to the total size of everything installed.

**Comment by carlashley** [comment]
There is now a very simple _n_ loops installed, _n_ downloaded summary that is logged to screen and the log file.

**Comment by apizz** [comment]
Is it possible to also add _n_ GBs installed?
