### ISSUE TITLE
Error while running appleLoops.py

### ISSUE THREAD

**Issue by rbuzzell** [carlashley/appleLoops#21]
I get this error when I try to run appleloops.py, on the first file it downloads. I've tried with several different flags and this keeps occurring

```
sudo ./appleLoops.py --apps garageband --mandatory-only --optional-only --mirror-paths --destination ~/Desktop/loops
Loops downloading to: /Users/rbuzzell/Desktop/loops (mirroring Apple folder structure.)
Copied existing file: MAContent10_AssetPack_0585_DrummerRootsGBLogic.pkg
Downloading: MAContent10_AssetPack_0376_EXS_GuitarsWarmElectric.pkg (Package size: 30.76 MB  Install size: 46.09 MB)
######################################################################## 100.0%
Traceback (most recent call last):
  File "./appleLoops.py", line 1512, in <module>
    main()
  File "./appleLoops.py", line 1504, in main
    al.main_processor()
  File "./appleLoops.py", line 575, in main_processor
    self.process_pkgs(self.get_feed(apple_url, fallback_url))  # NOQA
  File "./appleLoops.py", line 846, in process_pkgs
    download_or_install(_loop)
  File "./appleLoops.py", line 824, in download_or_install
    self.download(loop_pkg)
  File "./appleLoops.py", line 946, in download
    self.deployment_summary['downloaded_amount'] = self.deployment_summary['downloaded_amount'] + pkg.pkg_size  # NOQA
AttributeError: AppleLoops instance has no attribute 'deployment_summary'
```

**Comment by rbuzzell** [comment]
I've run it as follows and it doesn't seem to error, but it isn't putting files in the specified directory.

`sudo ./appleLoops.py --deployment --mandatory-only --optional-only --destination ~/Desktop/loops`

**Comment by apizz** [comment]
@rbuzzell because you're using `sudo` this runs as the root user.  Therefore, ~/Desktop/loops would correspond to the root user's Desktop, not your own.

Whenever I run sudo, I always try and be explicit and supply the full path to avoid any issues.

**Comment by rbuzzell** [comment]
Same result, even with a fully expanded destination directory.

**Comment by carlashley** [comment]
I'll have that fixed shortly.

**Comment by carlashley** [comment]
Resolved in commit ea72874

**Comment by carlashley** [comment]
@rbuzzell The exception error is fixed.
The only time that `sudo` needs to be used is when the `--deployment` flag is used to actually install the content.

**Comment by apizz** [comment]
Ahh good call

**Comment by rbuzzell** [comment]
That seems to have resolved it on my end, thank you :D
