### ISSUE TITLE
Script leaves off one loop every time.

### ISSUE THREAD

**Issue by TheBismarck** [carlashley/appleloops#21]
Hello,

When running the script with Logic 10.5 and Garageband installed, all installs just fine, but when launching Logic 10.5, one of the loops isn't installed. 

This occurs on all computers and the name of the package is: "MAContent10_AssetPack_0801_AppleLoopsPrismaticaB.pkg".

The script downloads package numbers up to 800, but not this one which is numbered 801

Version: Current 3.16

command: /usr/local/bin/appleloops --deployment --pkg-server http://server.domain.com/custom/appleloops -m -o --allow-untrusted

**Comment by carlashley** [comment]
Yes, the debug log is required.

**Comment by carlashley** [comment]
This particular loop doesn't seem to exist in any of the deployment test runs I've done with Logic Pro X 10.5 and GarageBand 10.3.4.

**Comment by macchrister** [comment]
I have the same problem, I'm missing lp10_ms3_content_2016/MAContent10_AssetPack_0801_AppleLoopsPrismaticaB.pkg everytime I'm trying to do a fresh install.

**Comment by carlashley** [comment]
I'm going to need debug logs, a copy of the GarageBand & Logic Pro X property lists on the machine's that this error happens on. Please zip them and attach them here.

The property lists are found in the `/Applications/<app>/Contents/Resources` folder and will be called `garageband1021.plist` and `logicpro1050.plist`.

I cannot replicate this in my own setup with fresh installs, and as mentioned in a previous comment, the loop does not exist in any of those two files I've tested.

**Comment by macchrister** [comment]
I did a quick look in the plist files and the package that is missing is not found in the plist files so I'ts apple that have done something wrong and not you. I don't have the time to do a debug log just now. If this persist after the summer I can try to do a debug log but I don't think its any bug in your script.

**Comment by carlashley** [comment]
From Slack:
```
jazzace  8:01 AM
Dug a little deeper. Installed the Essential Sounds+Loops, then separately installed Prismatica (Nu-Disco) using the GUI. Determined that the installation done that way and by appleLoops are the same except:
logicpro1050.plist includes MAContent10_AssetPack_0755_AppleLoopsPrismatica in its list;
the GUI does not download that pkg but instead downloads 0801_AppleLoopsPrismaticaB.
The pkgs install the same files by name, but the modification date of the loops are in July 2019 for the former and March-April 2020 for the latter. I used Charles (Proxy) to determine what Logic was downloading via the GUI. I did not see a redirect, but either the app is reading from an external list or it knows how to silently redirect for that one updated pkg. (edited)```
