### ISSUE TITLE
GarageBand optional install fail after initial run with --mandatory switch

### ISSUE THREAD

**Issue by bmhayward** [carlashley/appleLoops#22]
macOS 10.12.6
GarageBand 10.2.0

Initially running the following command before launching GarageBand on a fresh install of macOS 10.12.6:

/usr/local/bin/appleLoops.py --deployment --mandatory --cache-server [cacheServer URL]:[cachServer port#]

works as expected.

Running the following command afterwards:

/usr/local/bin/appleLoops.py --deployment --optional --cache-server [cacheServer URL]:[cachServer port#]

returns the following:

Loops downloading to: /tmp
Caching server: [caching server]
Processing loops from: garageband1020.plist
Skipping MAContent10_AssetPack_0296_AlchemySoundEffectsSynths.pkg
  Installing: MAContent10_AssetPack_0296_AlchemySoundEffectsSynths.pkg
Install failed, check /var/log/installer.log for any info: MAContent10_AssetPack_0296_AlchemySoundEffectsSynths.pkg
Skipping garageband as it does not appear to be installed.
Skipping logicpro as it does not appear to be installed.
Skipping mainstage as it does not appear to be installed.
Installed 0 packages, downloaded 0.00 B, install size 0.00 B
Not all loops installed: MAContent10_AssetPack_0296_AlchemySoundEffectsSynths.pkg

Nothing is installed and all processing stops.

Any help you can provide would be greatly appreciated.

Thanks,
Brent

**Comment by carlashley** [comment]
Try adding `--debug --log-path ~/Desktop` to the command that is failing and copypasta the results here.

**Comment by carlashley** [comment]
Commit 431f719 should it clearer when there is an exception that isn't caused by an app not being found/installed.

**Comment by bmhayward** [comment]
Carl,

This morning I went to test again with the debug command and everything works. If you still want the debug log (it’s big) let me know, otherwise you can go ahead and close this bug.

Thanks,
Brent

**Comment by carlashley** [comment]
Okay, no worries.
