### ISSUE TITLE
Specific Plug-ins missing 

### ISSUE THREAD

**Issue by jazzace** [carlashley/appleloops#23]
**Describe the bug**
When an AppleLoops installation of all loops and sounds is compared with an installation of all loops and sounds from the GUI, the AppleLoops version does not contain `/Library/Application Support/Logic/Plug-In Settings/Space Designer/05 Surround Spaces` and `06 HD Surround Spaces` nor their contents.

**Version**
3.1.9 (pre-release version 2020-07-20)

**Command Used**
/usr/local/bin/appleloops --deployment -m -o -q

**Debug Log**
AppleLoops functions as designed.

**Comment by jazzace** [comment]
As best as I can determine from the install.log, the missing installer is located at https://audiocontentdownload.apple.com/lp10_ms3_content_2013/MAContent10_IRsSurround.pkg
That installs the aforementioned two folders of items plus an additional folder of items in `/Library/Audio/Impulse Responses/Apple/04 Surround Spaces`

**Comment by carlashley** [comment]
I've spun up a fresh macOS 10.15.6 VM with Logic Pro X 10.5.1 installed and run through a complete deployment and not been able to replicate this specific issue - the package was `MAContent10IRsSurround.pkg` file was downloaded and installed correctly.

**Comment by jazzace** [comment]
I've now done separate installs on three different models running a clean version of macOS 10.15.6 and it works properly. Closing this issue as a "one-off" problem likely unrelated to AppleLoops.
