### ISSUE TITLE
Using --deployment with MainStage Keeps Downloading & Installing MAContent10_IRsSurround.pkg

### ISSUE THREAD

**Issue by apizz** [carlashley/appleLoops#23]
- Command used: appleLoops.py --deployment -m -o -c http://${CACHE_SERVER_IP} --log-path "$LOG_DIR" -t "$FREESPACE"

- Version: 2.1.7

- Debug log output: attached.  We're using a Caching Server and It appears that it's not seeing the `MAContent10_IRsSurround.pkg` file and going to Apple for it.  Odd that it's not already cached after these downloads.  Not convinced its an appleLoops.py problem, but wanted to put it out there.

[appleLoopsDEBUGLog_2.1.7.log](https://github.com/carlashley/appleLoops/files/1379515/appleLoopsDEBUGLog_2.1.7.log)

**Comment by carlashley** [comment]
Looking at the log, the package URL doesn't seem to be formatted with the caching server URL correctly.

`pkg_url=u'http://audiocontentdownload.apple.com/lp10_ms3_content_2013/MAContent10_IRsSurround.pkg'` should be formatted with your caching URL.

Not sure why that wouldn't be happening. Does this issue happening on subsequent runs on machines that haven't had the loops installed?

There's potential for a cache 'race' condition if the script is deployed on multiple machines simultaneously. Personally I think it's better to cache and host the packages locally, but obviously environmental configs are different for everyone.

**Comment by apizz** [comment]
@carlashley Yes the issue has happened on subsequent runs on several different machines I've tested with.

I only went with the caching server option because we already had one setup and required the least amount of changes on my end.

That being said, we moved a few things to a new server and it wouldn't be that challenging to move to the pkg server option, as you say.  With that I guess it's not terribly problematic, as it's only one package ... still my OCD brain says it does matter.

Anything else I can test?

**Comment by carlashley** [comment]
One of these things is not like the other...

```
[carl@blackbird]:~ # curl -I http://example.org:51006/lp10_ms3_content_2016/MAContent10_IRsSurround.pkg?source=audiocontentdownload.apple.com
HTTP/1.1 404 Not Found
X-Apple-Cache-Session: BxKrGUt7hr0D
Accept-Ranges: bytes
Content-Length: 0
Connection: close
Date: Thu, 16 Nov 2017 09:05:56 GMT


[carl@blackbird]:~ # curl -I http://example.org:51006/lp10_ms3_content_2013/MAContent10_IRsSurround.pkg?source=audiocontentdownload.apple.com
HTTP/1.1 200 OK
Content-Type: application/vnd.apple.installer+xml
X-Apple-Cached-Ranges: 1BD10A6C-6350-486F-B31A-A2B7B0D7E365 bytes=
Server: Apache
Expires: Thu, 16 Nov 2017 09:09:11 GMT
X-Apple-Cache-Session: YXI2pq+BZKOz
Cache-Control: max-age=60
Date: Thu, 16 Nov 2017 09:08:11 GMT
Content-Length: 506758576
Connection: keep-alive
Etag: "1e3485b0-4e130d4295140"
Accept-Ranges: bytes
Last-Modified: Wed, 10 Jul 2013 23:42:21 GMT
```

The year in the URL was incorrect. Changed the order of some code and this fixes the issue. A fix is available for testing in the test branch - commit 62eb90faabe4f8aac61d3919970a6d637b4dfe51.

**Comment by apizz** [comment]
schweet!

**Comment by carlashley** [comment]
Closing this issue - fix has been merged into master.
