### ISSUE TITLE
Using --pkg-server with client on different VLAN processes installed loop check VERY slowly

### ISSUE THREAD

**Issue by apizz** [carlashley/appleLoops#24]
In my testing, when a client requesting the appleLoops deployment is on a different VLAN than our pkg server (which it can download pkgs from just fine via a browser) from the logs it appears that it writes the apple loop pkg lookup / install check roughly every 5-6 seconds.

However, the same test client machine on the same VLAN as the pkg server write each lookup / install check to log between 40 - 70 **_milliseconds_**.  This is all happening wirelessly over our network.

It appears in the case of being on a different VLAN that rather than getting the pkg URL from the pkg server it's going out to Apple for this.  I've confirmed on the test client via a browser that it can download several PKGs just fine from the pkg server, so I'm wondering what appleLoops.py does in terms of querying for pkg checks that's causing this time disparity.

The pkg server is also our JSS box and distribution point, which all our managed Macs talk to and download packages from without issue.

In my tests I tried entering both the FQDN and the static IP for the pkg server and got the same results in terms of timing on the test client when on a different VLAN.

- Command used: sudo appleLoops.py --deployment --pkg-server http://pkgserver.com/appleLoops --allow-insecure --m --debug -t 10 --dry-run --log-path /Users/testuser/Desktop

- Version: 2.1.9

- Debug log output:

[appleLoops_copy.zip](https://github.com/carlashley/appleLoops/files/1478806/appleLoops_copy.zip)

**Comment by carlashley** [comment]
The 5-6 seconds suggests that maybe there is an issue causing the look up to exceed the `self.timeout` value of `5` seconds in the `Requests` class.

You can test this by increasing the value in the script to something like `10` (it needs to be an integer).

I've not been able to replicate the issue yet.

**Comment by apizz** [comment]
After the Christmas holiday I'll give this another look and do some more in depth testing and with the latest version.  Haven't had a moment!

**Comment by apizz** [comment]
Pretty sure this is a networking-related issue on our end.  I can confirm I can download individual packages as well as run appleLoops.py on a laptop wirelessly on the same VLAN as our pkg server as well as a desktop on a different VLAN.  For whatever reason can't do it wirelessly from a laptop on a different VLAN as our pkg server.

Closing this issue ...
