### ISSUE TITLE
FEATURE REQUEST: allow selecting app when deploying

### ISSUE THREAD

**Issue by MiqViq** [carlashley/appleLoops#26]
Thanks for creating a very useful tool!

I would like to see a change in code that will allow installing Apple Loops for only one app when deploying. To save the downtime.

Like:
appleLoops.py --apps garageband --deployment --force-deploy --mandatory-only --optional-only

**Comment by carlashley** [comment]
Definitely! This capability is in a current test build which happens to be a re-write. :)

**Comment by MiqViq** [comment]
Cool! Will the test build be available anytime soon?

**Comment by carlashley** [comment]
I haven't forgotten about this, life has just gotten very busy and this has been less of a priority for me to work on. I'd like to say I'd have something by the end of March, but I can't promise that.

**Comment by MiqViq** [comment]
No problemo.

Busy times here too.

**Comment by carlashley** [comment]
I'm closing this out - I've got plans to do this in the next version, but life keeps happening.

**Comment by MiqViq** [comment]
Any progrees with this?
