### ISSUE TITLE
feature: check file sizes

### ISSUE THREAD

**Issue by gaming-hacker** [carlashley/appleLoops#27]
any possibility to check downloaded filesizes versus the original files?  sometime the downloads get interrupted and it seems the script only check if the download file exists but not size. some kind of quick hash, md5, rmd, etc

**Comment by carlashley** [comment]
The script calls `curl` with the `-C -` command to resume downloading at `<offset>`. The specific argument used tells `curl` to try and work out the offset to resume from automatically.

I'd love to use a hash based check, but there's no known hash supplied by Apple to compare against.

Older versions used to have a custom download routine that would check the size of the local copy vs the remote, however I have stopped using that download method in favour of the simplicity of `curl`.
If you're still running a much older version, I'd suggest checking out the most recent release (if you're not already using it).

**Comment by apizz** [comment]
In the case where `--pkg-server` is used, could a hash be calculated as part of the PKG download on the package server?

**Comment by carlashley** [comment]
Yes it could, however this is not a feature I plan to implement unless Apple themselves start providing the hash for the package in their plist feed files. If it's something that is required in particular environments, feel free to fork and modify the fork :)
