### ISSUE TITLE
Orchestral Sounds missing Brass and Woodwinds downloads

### ISSUE THREAD

**Issue by GabeShack** [carlashley/appleloops#28]
**Describe the bug**
After running the deployment with -o we are seeing the full install missing some Orchestral Sounds.  Specifically under Brass missing all items and under woodwinds missing Bassoon Solo, Oboe, and Saxophone.

**Version**
3.2.2

**Command Used**
appleLoops --deployment -a garageband -o --log-level DEBUG

**Debug Log**
[appleloops.log.zip](https://github.com/carlashley/appleloops/files/5789235/appleloops.log.zip)

**Screenshots**

<img width="1437" alt="Screen Shot 2021-01-08 at 3 20 39 PM" src="https://user-images.githubusercontent.com/53574780/104060718-55832f80-51c5-11eb-8c7e-8490d820de98.png">
<img width="1435" alt="Screen Shot 2021-01-08 at 3 20 31 PM" src="https://user-images.githubusercontent.com/53574780/104060723-574cf300-51c5-11eb-8b96-f128bef9f946.png">
<img width="1437" alt="Screen Shot 2021-01-08 at 3 20 21 PM" src="https://user-images.githubusercontent.com/53574780/104060731-5a47e380-51c5-11eb-868c-7ec6ce2a8bca.png">

**Comment by carlashley** [comment]
Please give the v3.2.3 test release a try: https://github.com/carlashley/appleloops/releases/tag/v3.2.3.20210706
