### ISSUE TITLE
Skip Qualifying Apps?

### ISSUE THREAD

**Issue by PaulC2018** [carlashley/appleloops#29]
Hi,

I'm trying to get this setup as part of devices being deployed and managed via the Addigy MDM platform. The issue I'm having is that sometime this script arrives/runs before the Logic and GarageBand applications have arrived on the client device. Is there a way to make this app/script run 'dumber', ideally I don't care what applications are installed on the device at the time this code runs, I just want all the loops to start download from Apple's servers, regardless of if Logic, GarageBand or Mainstage in currently on the device as soon as possible.

Thanks

**Comment by carlashley** [comment]
Many of the audio content packages have install check scripts to verify a qualifying app are installed.

One way you could handle the issue of the script arriving before the applications is to use  a LaunchDaemon that watches `/Applications` to see if a qualifying application has been installed.
If you've never used watch folders - https://macissues.com/2015/02/02/how-to-use-launchagents-to-monitor-folder-contents-in-os-x/ (note, I can't provide any support for this).
