### ISSUE TITLE
Allow for appleLoops directory on pkgserver as well as appleloops?

### ISSUE THREAD

**Issue by apizz** [carlashley/appleloops#3]
**Describe the bug**
When attempting to deploy packages from on-prem package server using HTTP, produces error saying that `mirror server url format expected is https://example.org/appleloops or https://example.org/file.dmg`.

After some additional testing, it appears the real issue was that with v2 where everything was `appleLoops` instead of `appleloops` that the folder on our pkg server needed to be named `appleloops` in order to be processed.  Changing this caused packages to download and install as expected.

While it does say in the error message that it looks for a folder called appleloops, my initial assumption given the error message was that it was an HTTPS issue.

It seems to me that for those who used v2, appleLoops as a contained folder should be allowed, or a more explicit error message should point people to the unexpected folder name.

**Version**
3.0.1

**Command Used**
`appleloops --deployment -m --pkg-server http://internalorgserver.com/appleLoops`

**Comment by carlashley** [comment]
It was intentional, however the test wasn't working correctly in other tests, so it now only checks that a url path exists. v3.0.2 should resolve this.
