### ISSUE TITLE
Doesn't detect apps with versions

### ISSUE THREAD

**Issue by gaming-hacker** [carlashley/appleloops#31]
**Describe the bug**
my installed versions
MainStage 3.4.1.app
GarageBand_10.3.5.app

**Version**
The version of `appleloops.py` used. Can be found by using `./appleloops.py --version`.
3.2.3
**Command Used**
Please enter the complete command used.
./appleloops -m -o  -d /Volumes/Apps_Media/Library/all_apple_media --apps garageband mainstage logicpro

**Debug Log**
Processing Apple audio content, this may take some time.
Download destination is /Volumes/Apps_Media/Library/all_apple_media
No application installed for garageband, skipping
No application installed for mainstage, skipping
Processing logicpro1040.plist

**Comment by carlashley** [comment]
Please include the debug logs.

**Comment by carlashley** [comment]
Note: If you're _downloading_ content for apps that aren't installed, the `--apps` argument will fail. I suggest using `--fetch-latest garageband mainstage logicpro` instead.

**Comment by gaming-hacker** [comment]
Ok, I'll try new fetch latest.  The apps are installed but I change the default name of the app to include a version number because I have multiple versions of the apps.

**Comment by carlashley** [comment]
Ah yeah - that's kind of an edge case that I couldn't really plan on supporting. For downloading content in that kind of setup you could use either of these options:
- Use `--fetch-latest [app/s]` as mentioned
- Use `-p/--plists` to specify the exact source file to process content from
