### ISSUE TITLE
Qualifying copy of an app not found for JamPack1.pkg

### ISSUE THREAD

**Issue by apizz** [carlashley/appleLoops#32]
The machine in question was running 10.13.6 and had the latest version of GarageBand (10.3.1) installed.  As a result of this error, we get consistent reported failures when everything is actually working as expected.

Want to ensure appleLoops.py doesn't attempt to install a loops pkg that requires other Apple software that's not actually installed.

- Command used: _sudo appleLoops.py --deployment -m -o --pkg-server $PKG_SERVER -t 10 --log-path ~/Desktop --debug_

- Version: 2.2.2

- Debug log output:
[appleLoops.log.zip](https://github.com/carlashley/appleLoops/files/2246883/appleLoops.log.zip)

**Comment by carlashley** [comment]
Hey @apizz - thanks for the feedback. I've been slowly building up a new test version in the test branch, will look into the issue when I have a moment and aim to incorporate any fix into that test version.

**Comment by carlashley** [comment]
Should be resolved now per https://github.com/carlashley/appleLoops/commit/173c2b98f09c557fd27eb5c4629ab7f0d74b3ab6

**Comment by apizz** [comment]
Not sure if this is my own confusion or not, but when I downloaded a local copy of the test branch, when I ran appleLoops.py it still attempted to download the JamPack1.pkg and failed to install.

Running appleLoops3.py where the change was made results in the error below:

_ImportError: No module named concurrent.futures_

Removing this offending import in the script results in other failures
