### ISSUE TITLE
Crash when mirroring Apple folder structure.

### ISSUE THREAD

**Issue by chrisgrande** [carlashley/appleLoops#33]
- Command used:
`appleLoops.py --mirror-paths --apps garageband -d /Volumes/Munki/repo -m -o`

- Version:
version 2.2.3 (2018-08-05).

- Debug log output:
`Traceback (most recent call last):
  File "appleLoops.py", line 1601, in <module>
    main()
  File "appleLoops.py", line 1593, in main
    al.main_processor()
  File "appleLoops.py", line 625, in main_processor
    self.process_pkgs(self.get_feed(apple_url, fallback_url), os.path.basename(apple_url))  # NOQA
  File "appleLoops.py", line 928, in process_pkgs
    update_pkg_sizes(_loop)
  File "appleLoops.py", line 913, in update_pkg_sizes
    self.size_info['download_total'] = self.size_info['download_total'] + loop.pkg_size  # NOQA
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
`

**Comment by jmahlman** [comment]
I am seeing this same issue.

**Comment by jmahlman** [comment]
Chris, are you by chance using a Palo Alto device on your network? (see [this](https://github.com/carlashley/appleLoops/issues/34)

**Comment by carlashley** [comment]
Merged a PR which changed the Apple source URL's over to `https` - this _should_ resolve the issue if a Palo Alto device is on the network, but you'll still need to make sure relevant web addresses are whitelisted (see Web Access as referenced here: https://github.com/carlashley/appleLoops/wiki/Requirements-and-Support)

**Comment by chrisgrande** [comment]
We do have Palo Alto devices upstream from us, just tested and the fix works. Thanks Carl!
