### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by walkintom** [carlashley/appleloops#34]
**Describe the bug**
Performing a mandatory and optional run while specifying destination results  `TypeError: '>' not supported between instances of 'NoneType' and 'int'` error. Have tried with and without `sudo` and with and without `--http2`. Python version is 3.9.6.

`/usr/local/bin/python3.9 /usr/local/bin/appleloops --plists logicpro1050.plist -m -o -d /Volumes/Data/munki_repo/pkgs/appleloops
Processing Apple audio content, this may take some time.
Download destination is /Volumes/Data/munki_repo/pkgs/appleloops
Processing logicpro1050.plist
Discovered 33 mandatory packages to download (1.57 GB) and 731 optional packages to download (56.34 GB)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/appleloops/__main__.py", line 38, in <module>
  File "/usr/local/bin/appleloops/loopslib/process.py", line 122, in freespace_checks
  File "/usr/local/bin/appleloops/loopslib/disk.py", line 75, in freespace
  File "/usr/local/bin/appleloops/loopslib/disk.py", line 21, in convert
TypeError: '>' not supported between instances of 'NoneType' and 'int'
`

**Version**
appleloops 3.2.3 (2021-07-24) Apache-2.0 License

**Command Used**
`/usr/local/bin/python3.9 /usr/local/bin/appleloops --plists logicpro1050.plist -m -o  -d /Volumes/Data/munki_repo/pkgs/appleloops`

**Debug Log**
Logs only being created when run as sudo.
[appleloops_failed_installs.log](https://github.com/carlashley/appleloops/files/6961871/appleloops_failed_installs.log)
[appleloops.log](https://github.com/carlashley/appleloops/files/6961872/appleloops.log)

![Screenshot 2021-08-10 at 14 01 34](https://user-images.githubusercontent.com/6242598/128871423-3c847e23-6604-450f-913b-ded28168834d.png)

**Comment by walkintom** [comment]
Additional info. Have discovered that the issue only occurs when selecting the external disk as the destination. PPPC is allowing both Python and appleLoops full disk access.

If I select the local disk as the destination, it doesn't error out. The external disk is formatted as Mac OS Extended (Journaled) but this isn't been an issue in the past.

**Comment by carlashley** [comment]
It looks as though you're downloading to a network share. Currently the only disk checks being done are by using `diskutil` on physical volumes, not shares.

I'll have to experiment with that particular scenario.

**Comment by walkintom** [comment]
Just an update to your previous comment, the volume I was downloading to is a locally connected USB RAID rather than a mounted network share. I'll give the new build a try though and report back whether the issue still occurs.
