### ISSUE TITLE
3.2.4 - Output shows PKG only not URL

### ISSUE THREAD

**Issue by macmule** [carlashley/appleloops#36]
**Describe the bug**
With 3.2.4 the output gives the pkg name and not the URL

**Version**
3.2.4

**Command Used**
/usr/local/munki/munki-python /usr/local/bin/appleloops --apps garageband --destination /tmp/ --dry-run -o -m

**Debug Log**
Debug log attached, note this shows the URL's so it seems to be when printing to Terminal.
[appleloops.log](https://github.com/carlashley/appleloops/files/7397331/appleloops.log)

**Comment by carlashley** [comment]
That may or may not have been deliberate but happy to change it back.
