### ISSUE TITLE
build dmg issue

### ISSUE THREAD

**Issue by leegalan** [carlashley/appleLoops#36]
- Command used:
./appleLoops.py --apps garageband --build-dmg garageband_loops_180906.dmg -m -o -d ~/Documents/apple_audio

- Version: 2.2.3

- Debug log output:
curl: (56) Recv failure: Connection reset by peer
Traceback (most recent call last):
  File "./appleLoops.py", line 1601, in <module>
    main()
  File "./appleLoops.py", line 1593, in main
    al.main_processor()
  File "./appleLoops.py", line 625, in main_processor
    self.process_pkgs(self.get_feed(apple_url, fallback_url), os.path.basename(apple_url))  # NOQA
  File "./appleLoops.py", line 924, in process_pkgs
    download_or_install(_loop)
  File "./appleLoops.py", line 907, in download_or_install
    self.download(loop_pkg)
  File "./appleLoops.py", line 1026, in download
    subprocess.check_call(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--progress-bar', '-L', '-C', '-', u'http://audiocontentdownload.apple.com/lp10_ms3_content_2016/MAContent10_AssetPack_0599_GBLogicAlchemyEssentials.pkg', '--create-dirs', '-o', u'/Users/setup/Documents/apple_audio/garageband1012/mandatory/MAContent10_AssetPack_0599_GBLogicAlchemyEssentials.pkg', '--user-agent', 'appleLoops/2.2.3']' returned non-zero exit status 56

**Comment by carlashley** [comment]
I've tried replicating this issue, but the downloads and dmg build worked fine for me. I'd say something happened when you tried to run it. Give it another go, and don't forget to make sure any proxy in the way whitelists the two URL's per 
https://github.com/carlashley/appleLoops/wiki/Requirements-and-Support
