### ISSUE TITLE
QUESTION: using appleLoops.py to download content on Linux server?

### ISSUE THREAD

**Issue by MiqViq** [carlashley/appleLoops#38]
Is it possible to use using appleLoops.py to download content on Linux server?

**Comment by MiqViq** [comment]
Umm...linux has no necessary Foundation module:
  File "/opt/public/AppleLoops/appleLoops.py", line 49, in <module>
    from Foundation import NSData  # NOQA
ImportError: No module named Foundation

I tested with a macOS 10.11 computer with working internet connection and it will download all loops with this command:
# download all apple loops for all apps WITHOUT installing them
appleLoops.py --mandatory-only --optional-only --apps garageband logicpro mainstage --mirror-paths --destination /Users/Shared/AppleLoops

After that you can copy the resulting directories within /Users/Shared/AppleLoops to your own web server if needed.

**Comment by carlashley** [comment]
Installing the required modules for this to work on Linux is quite problematic/painful. This is really built for running on macOS. If you need to get the loops into a Linux web server, download them on a Mac and then move them to the Linux box.
