### ISSUE TITLE
Logic Pro X 10.4.2 not satisfied with mandatory installed items

### ISSUE THREAD

**Issue by MiqViq** [carlashley/appleLoops#39]
After initial install of mandatory sounds Logic Pro X 10.4.2 still asks to download sounds worth of roughly 330 MB.

- Command used: 
appleLoops.py --deployment -m

- Version:
2.2.3

- Debug log output:
Loops downloading to: /tmp
Skipping garageband as it does not appear to be installed.
Processing loops from: logicpro1042.plist
Processing loops from: mainstage340.plist
Installed 0 packages, downloaded 0.00 B, install size 0.00 B

Tried to remove all Apple Loops pkg receipts which is not succeeding for some reason?
IFS=$'\n'
for aReceipt in $(pkgutil --pkgs | grep apple.pkg.MAContent)
do
	pkgutil --forget "$aReceipt"
done

**Comment by carlashley** [comment]
Apple loop package receipts get out in a SIP protected location. Please use the forced deployment argument and the debug argument and post logs back. Use `--help` to see how.

**Comment by carlashley** [comment]
Is this still an issue?

**Comment by MiqViq** [comment]
Inconvienence mostly but cannot be fixed with appleLoops.py
