### ISSUE TITLE
No more --mute-progress-bar?

### ISSUE THREAD

**Issue by apizz** [carlashley/appleloops#4]
**Describe the bug**
When running appleloops run with `--mute-progress-bar`, says it's an unrecognized verb.

In version 2, this was useful for keeping the logs clean when triggering appleloops as part of a Jamf script or munki nopkg script.

**Version**
3.0.1

**Command Used**
`appleloops --deployment -m --pkg-server http://internalorgserver.com/appleloops --mute-progress-bar`

**Comment by carlashley** [comment]
Dropping `--mute-progress-bar` is intentional. v3.0.2 implements `-q/--quiet` to drop the progress bar.
