### ISSUE TITLE
LPX Jam Pack 1 Instruments not installing / JamPack1.pkg install loop

### ISSUE THREAD

**Issue by ewtilman** [carlashley/appleLoops#40]
appleLoops.py seems to install everything fine but LPX says its missing Jam Pack 1 - Instruments portion (attached screenshot), then every time I run the appleLoops script it re-installs JamPack1.pkg

- Command used: sudo /usr/local/bin/appleLoops.py --deployment --pkg-server SERVERADDRESS -m -o

- Version: 2.2.3

- Debug log output:
2018-12-06 09:07:00,424 - appleLoops - INFO - Downloading: JamPack1.pkg (Package size: 12.20 MB  Install size: 317.75 MB)
2018-12-06 09:07:00,990 - appleLoops - DEBUG - Not in dry run, so attempting to install JamPack1.pkg
2018-12-06 09:07:00,990 - appleLoops - INFO -   Installing: JamPack1.pkg
2018-12-06 09:07:02,319 - appleLoops - INFO -   Installed: JamPack1.pkg
2018-12-06 09:07:02,322 - appleLoops - INFO - Skipping mainstage as it does not appear to be installed.
2018-12-06 09:07:02,322 - appleLoops - INFO - Installed 1 packages, downloaded 12.20 MB, install size 317.75 MB

![jampack1-instruments](https://user-images.githubusercontent.com/45667632/49600798-e75e4580-f938-11e8-8374-fc8818288681.JPG)

**Comment by hansen-m** [comment]
Me too!

**Comment by carlashley** [comment]
Try pulling the loop direct from Apple by removing the `--pkg-server` argument. You may have a 'stale' package in your local mirror.

Apple do occasionally update existing packages.

If that fails, run using the debug argument and post logs back here.

**Comment by ewtillman** [comment]
![image](https://user-images.githubusercontent.com/30277816/51341441-2b6b5c80-1a46-11e9-8544-e3015c4a6c41.png)

Apparently deleting the JamPack1.pkg file then running appleloops to update the repository would put back the old file.  Even deleting all files in the lp10_ms3_content_2013 and running appleloops to refresh would pull all new files from apple but restore the JamPack1.pkg file that was old as you can see from the screen shot date modified.  In the end I dumped the whole repository and was able to do a fresh pull from apple.  Then our macs were able install the updated JamPack1.pkg file successfully.

So you were correct the repository had a stale file that took a little effort to get updated.
Thanks for the assistance and script.
