### ISSUE TITLE
Using with Jamf Pro

### ISSUE THREAD

**Issue by leegalan** [carlashley/appleLoops#41]
- Command used: appleLoops.py --deployment -m -o --mute-progress-bar --allow-untrusted

- Version: Sept 28, 2018

- Debug log output: None

I was wondering if there's a way to modify this script to use it with Jamf Pro. The $1, $2, and $3 parameters passed in by jamf are causing the script to fail. Thanks,

Leeroy

**Comment by carlashley** [comment]
I don't really use JAMF, so your best bet is to check out the MacAdmin's Slack #musicsupport - there are several JAMF admin's there that can assist with what they do in their environments.
