### ISSUE TITLE
Loops for Logic 10.4.4 and Garageband 10.3.2

### ISSUE THREAD

**Issue by AndyC-CMTC** [carlashley/appleLoops#42]
Hi

The latest plists do not appear to indicate that these versions are supported.  Is that correct or have there been no loop updates recently and the script still works / updates on these newer versions?

Many thanks

Andy

**Comment by carlashley** [comment]
Hey @AndyC-CMTC - sorry for the very late reply!

The loops for Logic Pro X 10.4.4 appear to be the same as those released in Logic Pro X 10.4.2, at least based on the quick look at the Logic Pro X content plist.

The loops for GarageBand 10.3.2 also appear to be the same as those released for GarageBand 10.2.1, again based on the quick look at the GarageBand content plist.
