### ISSUE TITLE
AppleLoops Error

### ISSUE THREAD

**Issue by c0up3** [carlashley/appleloops#44]
- Command used:
sudo /usr/local/bin/appleLoops.py --log-path ~/Desktop -o --cache-server http://****:49408 --force-deploy --apps logicpro -b ~/Desktop/mainstage.dmg

(any command I use will fail)
sudo /usr/local/bin/appleLoops.py --log-path ~/Desktop -o --cache-server http://****:49408 --force-deploy --apps mainstage -b ~/Desktop/mainstage.dmg

- Version:
This is Fine

- Debug log output:
Copied existing file: MAContent10_AssetPack_0327_AppleLoopsJamPackRemixTools.pkg
Copied existing file: MAContent10_AssetPack_0436_EXS_TexturesPadsOvertone.pkg
Traceback (most recent call last):
  File "/usr/local/bin/appleLoops.py", line 1601, in <module>
    main()
  File "/usr/local/bin/appleLoops.py", line 1593, in main
    al.main_processor()
  File "/usr/local/bin/appleLoops.py", line 631, in main_processor
    self.process_pkgs(self.get_feed(apple_url, fallback_url), os.path.basename(apple_url))  # NOQA
  File "/usr/local/bin/appleLoops.py", line 928, in process_pkgs
    update_pkg_sizes(_loop)
  File "/usr/local/bin/appleLoops.py", line 913, in update_pkg_sizes
    self.size_info['download_total'] = self.size_info['download_total'] + loop.pkg_size  # NOQA
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by carlashley** [comment]
This should be resolved in commit e44dc948ee636bd88e7134776480f13ea1a77295.
