### ISSUE TITLE
Cache Server! How?

### ISSUE THREAD

**Issue by BaddMann** [carlashley/appleLoops#6]
I love your code, very clean very functional and very pluggable into munki, JSS and just about anything else.

I've been creating a "Cache" Server of all these downloads for a while with get_audio.content.py from https://github.com/cwindus/garageband.

When it Downloads, it just reproduces the File Structure of the HTTP source, is there any chance that your script can reproduce the source in this same fashion?

That way I can update my Cache server with this script as well as using it to provide the clients with their needs....

Thank you in advance!

**Comment by carlashley** [comment]
I'm not entirely sure I understand what you're trying to do?
There is the `-c http://url:port` or `--cache-server http://url:port` flag you can use which will pull the loop content through the specified Apple Caching Server, which will make any future downloads of the loop content come from the Apple Caching Server (GarageBand/Logic Pro X and MainStage 3 are all Caching Server aware from what I've observed in my testing).

Example:
```./appleLoops.py -c http://localcachingserver:49870 -m -f garageband1016.plist -d ~/Desktop/loops```
This downloads all the mandatory loops available for GarageBand versions that use the loops released in GarageBand 10.1.6 and stores them in the `loops` folder on your desktop.
I've changed the behaviour of the output folder structure to now put the loops into a folder for the release they appeared in, this is my preferred means of organising them, as it makes importing into `munki` trivial, and makes it clear which loop is for which release.

Also, the old `cwindus` repo is no longer actively supported and maintained, instead, the script is now supported & maintained here.

**Comment by BaddMann** [comment]
I'm aware "get_audio.content.py" is not supported anymore, but I started "my" caching server a while ago based on it. 

I was actually making a replica on a standard http server. Just had to reproduce the directory structure of the "http://audiocontentdownload.apple.com" site on my server and your Script was able to download directly from it. It failed about 30 in because I was missing (404) a PKG, but otherwise worked like a charm.

I was not aware that this works with Apple Caching server! That's cool, though it's failing in the same place as my method at about 30 pkgs in garageband download... But with a 502 error..

```
Downloading 19 of 35: MAContent10_AssetPack_0048_AlchemyPadsDigitalHolyGhost.pkg [100.00% of 11.27MB]
Downloading 20 of 35: MAContent10_AssetPack_0317_AppleLoopsModernRnB1.pkg [100.00% of 16.60MB]
Traceback (most recent call last):
  File "./appleLoops.py", line 859, in <module>
    main()
  File "./appleLoops.py", line 855, in main
    loops.main_processor()
  File "./appleLoops.py", line 641, in main_processor
    self.download(loop, counter)
  File "./appleLoops.py", line 553, in download
    raise e
urllib2.HTTPError: HTTP Error 502: Bad Gateway
```

I guess if I can figure out why I'm getting the 502 error on my apple caching server, I don't need to build the NGINX server I was going to use as a caching server. Thank goodness, because that was a huge rabbit hole I really don't have time to explore.

**Comment by carlashley** [comment]
Are you running `appleLoops.py` behind proxies/NAT/etc? I've done a fair bit of testing in the two environments I have access too and not come across a 502 error (which being a 5xx error indicates theres an issue with a server outside of your control).
What is the full command & options you're using when you get the error?

**Comment by BaddMann** [comment]
I'm behind a NAT with possible QOS rules that may of been the cause of my issues.
After I ran the script again the caching server had time to catch up and I've not seen the error since.
It appears to only happen if the cache server has none of the packages cached and is trying to cache as fast as possible.  At least that is how it appears on my Mac mini server...

**Comment by carlashley** [comment]
Ok cool :) I'll close this issue out then.
