### ISSUE TITLE
Partial Downloads or Missing Downloads

### ISSUE THREAD

**Issue by BaddMann** [carlashley/appleLoops#7]
Any chance we can add a flag to the script that compare's the Receipts of installs and only downloads the files that are missing a corresponding recipe? 

I'm currently messing with this bash script as a base: 
`pkgutil --packages | grep MAContent`

Of course as you're querying the plists, you have an array of all the package names, hopefully all the receipts are comparable.

Is this a far off idea?

**Comment by carlashley** [comment]
I'm not averse to the idea; the primary intent of this tool is a standalone means of downloading the audio content for admins that don't want to (or can't) have GarageBand/Logic Pro/MainStage installed on their workstation.

IMO, best practice for deployments is to use a patch management approach with the loops; so if you're a munki user, that would be importing the downloaded packages and adding them as an update for the audio apps that need it. If you use JAMF, then it would probably involve importing the loops and assigning some policy/scope (I don't have a JAMF instance to test with in order to understand best practice for JAMF).

If such a feature was to be implemented, it would be a specific flag/option rather than default behaviour, i.e. `./appleLoops.py --skip-installed <other options>`.

**Comment by BaddMann** [comment]
I'm currently using Munki and Casper.
I needed to provide GB and LOGIC downloads.
My previous efforts have resulted in tons of GBs of data in my munki repo that is an uncontrolled mess. 600GB plus or minus

It was a major pain in the rear end to get there and then every few months apple would release new Loops, that my Faculty suddenly "Had To have!". 

I want to destroy my current mess, then use your script to get the Loops as needed now, and re-import them.

I also want scripts within casper that will allow my techs to quickly install any missing loops that have suddenly materialized since the repo was built, but I don't want them to download pkgs that are already installed.

Once I get the opportunity I want to use a mac  freshly imaged to detect what it has from munki then download only the new stuff so that my import process is not littered with tons of useless pkgs that may or may-not already be within Munki. That way I'm not waiting 4+ hours to upload new 4GBs.

Of course I'm also planning on using my caching server as efficiently as possible! 
I'm an Admin that likes redundancy so this may not seem logical if I have another method that already works. It's Just me.

**Comment by carlashley** [comment]
@BaddMann If you're able to take a look at the current test branch, there are changes that may help deal with deploying loops.

**Comment by BaddMann** [comment]
I'll give it a try today.
Thank You.

**Comment by carlashley** [comment]
This issue is now resolved with the 2.0.x releases currently in testing.

**Comment by BaddMann** [comment]
Wonderful!! Your new Deployment Script Is awesome....

But of course I found something not working, (Im never happy :P)
When trying to update my Mirror I get the following errors:
`ht1-122-k11-m:appleLoops-test alpha$ sudo ./appleLoops.py --apps garageband mainstage logic --mirror-paths --destination ~/Desktop/loops
Starting run at 2017-08-02 10:28:18
Loops downloading to: /Users/alpha/Desktop/loops (mirroring Apple folder structure).
Traceback (most recent call last):
  File "./appleLoops.py", line 1283, in <module>
    main()
  File "./appleLoops.py", line 1275, in main
    al.main_processor()
  File "./appleLoops.py", line 455, in main_processor
    self.process_pkgs(self.get_feed(apple_url, fallback_url))  # NOQA
  File "./appleLoops.py", line 621, in process_pkgs
    if _pkg_installed:
UnboundLocalError: local variable '_pkg_installed' referenced before assignment`

I've not done enough research yet, will update if I find more!
Otherwise your script May make my Deployment of the big three apps finally bare-able!

Sorry for the late reply, I've been upgraded to Config Manager and windows 10 Guru as well 👍

**Comment by carlashley** [comment]
@BaddMann - that `pkg_installed referenced before assignment` issue should be resolved in 5e10b76.
