### ISSUE TITLE
installer cmd has a failing flag: --allowUntrusted

### ISSUE THREAD

**Issue by MiqViq** [carlashley/appleloops#7]
**Describe the bug**
installer cmd has a failing flag:
invalid option --allowUntrusted
SHOULD BE: -allowUntrusted with only one hyphen
without the flag pkg gets installed ok but with thefaulty flag, no go.

**Version**
3.0.7
macOS 10.14.6

**Command Used**
appleloops --log-level DEBUG --deployment -m -i -u --pkg-server http://soundserver.org/AppleLoops

**Debug Log**
Analysing...
Installed apps found: Logic Pro X (10.4.6)
Mandatory packages download/install size: 839.79 MB/1.08 GB (9 packages)
All packages download/install size: 839.79 MB/1.08 GB (9) packages

Downloading 1 of 9 - http://soundserver.org/AppleLoops/lp10_ms3_content_2016/MAContent10_AssetPack_0557_IRsSharedAUX.pkg
######################################################################## 100.0%
Installing 1 of 9 - MAContent10_AssetPack_0557_IRsSharedAUX.pkg
 Error installing MAContent10_AssetPack_0557_IRsSharedAUX.pkg. '/var/log/install.log' may include additional information.

DEBUG - /usr/sbin/installer --allowUntrusted -pkg /tmp/appleloops/lp10_ms3_content_2016/MAContent10_AssetPack_0593_DrummerSoCalGBLogic.pkg -target /: installer: invalid option --allowUntrusted

**Screenshots**

**Comment by apizz** [comment]
@MiqViq Your syntax is wrong.  Run `appleloops -h` >> `-u, --allow-untrusted`

**Comment by MiqViq** [comment]
> @MiqViq Your syntax is wrong. Run `appleloops -h` >> `-u, --allow-untrusted`

No it is not. I am giving a cmd with -u like appleloops is informing. Appleloops itself is giving a wrong flag to installer.

**Comment by apizz** [comment]
I'm really sorry, I read too quickly 🤕

**Comment by carlashley** [comment]
This should be resolved now in v3.0.8. I haven't created a release yet, so pull the latest version and use the installer in `dist/pkg` or the `appleloops` file for testing.

**Comment by carlashley** [comment]
Closing this issue out - haven't heard any issues about the latest patch.
