### ISSUE TITLE
Looping on six legacy packages

### ISSUE THREAD

**Issue by sramdeen** [carlashley/appleloops#8]
**Describe the bug**
Six 'legacy' packages are installed on every run of appleloops. 

debug log attached. 

I'm not sure if this is the cause but, on examining the latest garageband and logic plists at audiocontentdownload.apple.com and using "MAContent10_AppleLoopsLegacy1" as an example of one of the offending packages, some of the defined FileCheck paths do not seem to exist on the client after appleloops has installed the package:

/Library/Application Support/GarageBand/Apple Loops/Apple Loops for GarageBand Jam Pack/12 String Dream 01.aif **(The "Apple Loops" folder does not exist at all)**
/Library/Audio/Apple Loops/Apple/Jam Pack 1/12 String Dream 01.aif **(file does not exist)**
/Library/Audio/Apple Loops/Apple/Jam Pack 1/12 String Dream 01.caf **(this one is present)**

I'm not sure if the FileCheck routine is an 'and' or an 'or', but if I `touch "/Library/Application Support/GarageBand/Apple Loops/Apple Loops for GarageBand Jam Pack/12 String Dream 01.aif"` and `touch "/Library/Audio/Apple Loops/Apple/Jam Pack 1/12 String Dream 01.aif"` and run appleloops again, it considers MAContent10_AppleLoopsLegacy1 installed, so I'm guessing it's an 'and' check.

Looking at `pkgutil --files com.apple.pkg.MAContent10_AppleLoopsLegacy1`, I can only see "Library/Audio/Apple Loops/Apple/Jam Pack 1/12 String Dream 01.caf" listed in the output.

**Version**
3.0.7
macOS 10.14.6

**Command Used**
appleloops --deployment -m -o -l DEBUG

**Debug Log**
[appleloops.log](https://github.com/carlashley/appleloops/files/3537073/appleloops.log)

**Comment by carlashley** [comment]
It is an `and` check. Will have a look at how best to handle this type of scenario - the file check is a new process in this version so thanks for raising that :)

**Comment by carlashley** [comment]
@sramdeen do you happen to have a list of the six packages this happens on? I no longer have access to a machine that has enough space to install all the packages.

**Comment by carlashley** [comment]
This should be resolved now in v3.0.8. I haven't created a release yet, so pull the latest version and use the installer in `dist/pkg` or the `appleloops` file for testing.

**Comment by carlashley** [comment]
Closing this issue out - haven't heard any issues about the latest patch.
